In [59]:
'''
对T+CLOUD上的收发存汇总表进行二次开发，与公司以前的格式一致
'''
import os
import numpy as np
import easygui
import pandas as pd
import openpyxl

In [104]:
lst = [
'存货分类 (1级)',
 '存货分类 (2级)',
 '存货分类 (3级)',
 '存货分类 (4级)',
 '存货分类 (5级)',
 '存货编码',
 '存货',
 '存货代码',
  '数量(主单位)',
 '平均单价',
 '金额',
 '数量(辅单位)',
 '计量单位组合',
 '数量(主单位).1',
 '平均单价.1',
 '金额.1',
 '数量(辅单位).1',
 '计量单位组合.1',
 '数量(主单位).2',
 '平均单价.2',
 '金额.2',
 '数量(辅单位).2',
 '计量单位组合.2',
 '数量(主单位).3',
 '平均单价.3',
 '金额.3',
 '辅数量',
 '计量单位组合.3']

lst2 = [
'class01',
 'class02',
 'class03',
 'class04',
 'class05',
 'code',
 'stock',
 'content',
  'begin_ben',
 '平均单价',
 '金额',
 'begin_jian',
 '计量单位组合',
 'ruku_ben',
 '平均单价.1',
 '金额.1',
 'ruku_jian',
 '计量单位组合.1',
 'chuku_ben',
 '平均单价.2',
 '金额.2',
 'chuku_jian',
 '计量单位组合.2',
 'end_ben',
 '平均单价.3',
 '金额.3',
 'end_jian',
 '计量单位组合.3']

lst3 =  [
 'class02',
 'class05',
 'code',
 'stock',
 'content',
 'begin_jian',
 'ruku_jian',
 'chuku_jian',
 'end_jian',
]

lst_result0 = ['class05','code','stock',
             'content',
             'begin_jian','yesterday_jian',
             'yesterday_ruku','ruku_jian',
              'yesterday_chuku','chuku_jian',
               'end_jian']

lst_result0 = ['类别','货号','品名',
             '含量',
             '月初','上日',
             '本日入库','入库累计',
              '本日出库','出库累计',
               '结余']


fname = r"F:\a00nutstore\008\zw08\用友报价\产成品库存\收发存汇总表01.xlsx"

def chuli(fname):
    df =  pd.read_excel(fname,skiprows = 7)
    df = df.iloc[:,1:]
    df.columns = lst
    df.columns = lst2
    df['content'] = df['end_ben']/df['end_jian']
    df = df[df['class01'] != '制表人:']
    df = df[df['class01'] != '合计：']
    df = df[df['class01'].notnull()]
    df = df[lst3]
    return df
df1 = chuli(fname)
df1

,class02,class05,code,stock,content,begin_jian,ruku_jian,chuku_jian,end_jian
0,抄本,材料纸,DB501,单行材料纸,500.0,150.0,NaN,2.0,148.0
1,抄本,材料纸,FB503,方格材料纸,500.0,98.0,NaN,NaN,98.0
2,抄本,材料纸,J1601,简装双行材料纸,270.0,81.0,NaN,NaN,81.0
3,抄本,材料纸,J1602,简装单行材料纸,270.0,115.0,NaN,NaN,115.0
4,抄本,材料纸,J1603,简装方格材料纸,270.0,54.0,NaN,NaN,54.0
...,...,...,...,...,...,...,...,...,...
1526,账本,装订配件,L16KPP,16KPP账夹（立信孔）,260.0,20.0,NaN,NaN,20.0
1527,账本,装订配件,存料卡,48K存料卡,5400.0,52.0,NaN,NaN,52.0
1528,账本,装订配件,固定资产明细卡,30K固定资产明细卡,3000.0,16.0,NaN,NaN,16.0
1529,账本,装订配件,商品卡,48K商品卡,5400.0,21.0,NaN,NaN,21.0
1530,账本,装订配件,账钉,账钉,100.0,8.0,NaN,NaN,8.0

In [105]:
fname2 = r"F:\a00nutstore\008\zw08\用友报价\产成品库存\收发存汇总表02.xlsx"
df2 = chuli(fname2)

In [106]:
lst01_yesterday =  [
 'class02',
 'class05',
 'code',
 'stock',
 'begin_jian',
 'ruku_jian',
 'chuku_jian',
]
lst02_yesterday =  [
 'class02',
 'class05',
 'code',
 'stock',
 'yesterday_jian',
 'yesterday_ruku',
 'yesterday_chuku',

]
df1 = df1[lst01_yesterday]
df1.columns = lst02_yesterday
df1

,class02,class05,code,stock,yesterday_jian,yesterday_ruku,yesterday_chuku
0,抄本,材料纸,DB501,单行材料纸,150.0,NaN,2.0
1,抄本,材料纸,FB503,方格材料纸,98.0,NaN,NaN
2,抄本,材料纸,J1601,简装双行材料纸,81.0,NaN,NaN
3,抄本,材料纸,J1602,简装单行材料纸,115.0,NaN,NaN
4,抄本,材料纸,J1603,简装方格材料纸,54.0,NaN,NaN
...,...,...,...,...,...,...,...
1526,账本,装订配件,L16KPP,16KPP账夹（立信孔）,20.0,NaN,NaN
1527,账本,装订配件,存料卡,48K存料卡,52.0,NaN,NaN
1528,账本,装订配件,固定资产明细卡,30K固定资产明细卡,16.0,NaN,NaN
1529,账本,装订配件,商品卡,48K商品卡,21.0,NaN,NaN
1530,账本,装订配件,账钉,账钉,8.0,NaN,NaN

In [107]:
merge = pd.merge(df2,df1,how = 'left',on = ['class02','class05','code','stock']) 
merge

,class02,class05,code,stock,content,begin_jian,ruku_jian,chuku_jian,end_jian,yesterday_jian,yesterday_ruku,yesterday_chuku
0,抄本,材料纸,DB501,单行材料纸,500.0,150.0,NaN,2.0,148.0,150.0,NaN,2.0
1,抄本,材料纸,FB503,方格材料纸,500.0,98.0,NaN,NaN,98.0,98.0,NaN,NaN
2,抄本,材料纸,J1601,简装双行材料纸,270.0,81.0,NaN,NaN,81.0,81.0,NaN,NaN
3,抄本,材料纸,J1602,简装单行材料纸,270.0,115.0,NaN,NaN,115.0,115.0,NaN,NaN
4,抄本,材料纸,J1603,简装方格材料纸,270.0,54.0,NaN,NaN,54.0,54.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
1526,账本,装订配件,L16KPP,16KPP账夹（立信孔）,260.0,20.0,NaN,NaN,20.0,20.0,NaN,NaN
1527,账本,装订配件,存料卡,48K存料卡,5400.0,52.0,NaN,NaN,52.0,52.0,NaN,NaN
1528,账本,装订配件,固定资产明细卡,30K固定资产明细卡,3000.0,16.0,NaN,NaN,16.0,16.0,NaN,NaN
1529,账本,装订配件,商品卡,48K商品卡,5400.0,21.0,NaN,NaN,21.0,21.0,NaN,NaN
1530,账本,装订配件,账钉,账钉,100.0,8.0,NaN,NaN,8.0,8.0,NaN,NaN

In [65]:
lst_merge = ['class02','class05','code','stock',
             'content',
             'begin_jian','yesterday_jian',
             'yesterday_ruku','ruku_jian',
              'yesterday_chuku','chuku_jian',
               'end_jian']
merge = merge[lst_merge]
merge

,class02,class05,code,stock,content,begin_jian,yesterday_jian,yesterday_ruku,ruku_jian,yesterday_chuku,chuku_jian,end_jian
0,抄本,材料纸,DB501,单行材料纸,500.0,150.0,150.0,0.0,0.0,2.0,2.0,148.0
1,抄本,材料纸,FB503,方格材料纸,500.0,98.0,98.0,0.0,0.0,0.0,0.0,98.0
2,抄本,材料纸,J1601,简装双行材料纸,270.0,81.0,81.0,0.0,0.0,0.0,0.0,81.0
3,抄本,材料纸,J1602,简装单行材料纸,270.0,115.0,115.0,0.0,0.0,0.0,0.0,115.0
4,抄本,材料纸,J1603,简装方格材料纸,270.0,54.0,54.0,0.0,0.0,0.0,0.0,54.0
...,...,...,...,...,...,...,...,...,...,...,...,...
1526,账本,装订配件,L16KPP,16KPP账夹（立信孔）,260.0,20.0,20.0,0.0,0.0,0.0,0.0,20.0
1527,账本,装订配件,存料卡,48K存料卡,5400.0,52.0,52.0,0.0,0.0,0.0,0.0,52.0
1528,账本,装订配件,固定资产明细卡,30K固定资产明细卡,3000.0,16.0,16.0,0.0,0.0,0.0,0.0,16.0
1529,账本,装订配件,商品卡,48K商品卡,5400.0,21.0,21.0,0.0,0.0,0.0,0.0,21.0
1530,账本,装订配件,账钉,账钉,100.0,8.0,8.0,0.0,0.0,0.0,0.0,8.0

In [108]:
merge1 = merge.copy()
merge1

,class02,class05,code,stock,content,begin_jian,ruku_jian,chuku_jian,end_jian,yesterday_jian,yesterday_ruku,yesterday_chuku
0,抄本,材料纸,DB501,单行材料纸,500.0,150.0,NaN,2.0,148.0,150.0,NaN,2.0
1,抄本,材料纸,FB503,方格材料纸,500.0,98.0,NaN,NaN,98.0,98.0,NaN,NaN
2,抄本,材料纸,J1601,简装双行材料纸,270.0,81.0,NaN,NaN,81.0,81.0,NaN,NaN
3,抄本,材料纸,J1602,简装单行材料纸,270.0,115.0,NaN,NaN,115.0,115.0,NaN,NaN
4,抄本,材料纸,J1603,简装方格材料纸,270.0,54.0,NaN,NaN,54.0,54.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
1526,账本,装订配件,L16KPP,16KPP账夹（立信孔）,260.0,20.0,NaN,NaN,20.0,20.0,NaN,NaN
1527,账本,装订配件,存料卡,48K存料卡,5400.0,52.0,NaN,NaN,52.0,52.0,NaN,NaN
1528,账本,装订配件,固定资产明细卡,30K固定资产明细卡,3000.0,16.0,NaN,NaN,16.0,16.0,NaN,NaN
1529,账本,装订配件,商品卡,48K商品卡,5400.0,21.0,NaN,NaN,21.0,21.0,NaN,NaN
1530,账本,装订配件,账钉,账钉,100.0,8.0,NaN,NaN,8.0,8.0,NaN,NaN

In [109]:
gp = merge1.groupby('class02')
gp

In [112]:
gp = merge1.groupby('class02')
def xiaojiClass05(gp2,key,d):
    d = d[lst_result0]
    d.loc[key] = d.sum()
    d.iloc[-1,:4] = [key + '小计','','','']
    return d

In [114]:
filename = '收发存汇总表.xlsx'
wb = openpyxl.Workbook()
wb.save(filename)

for name,gp002 in gp: 
    table = pd.pivot_table(gp002,index = ['class05','code'],aggfunc = sum)
    table = table.reset_index()
    gp2 = table.groupby('class05')
    
    heji = pd.DataFrame(gp002).sum()
    data = []
    for key,gp005 in gp2:
        df05 = xiaojiClass05(gp2,key,gp005)
        data.append(df05)
    df005 = pd.concat(data)
    df005 = df005[lst_result0]
    df005.loc[name] = heji
    df005.iloc[-1,:4] = [name + '合计','','','']
    with pd.ExcelWriter(filename, engine='openpyxl', mode='a', if_sheet_exists='overlay') as writer:
        df005.to_excel(writer, sheet_name=name, index=False)

C:\Users\redda\AppData\Local\Temp\ipykernel_9920\3662095207.py:6: FutureWarning: The provided callable <built-in function sum> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  table = pd.pivot_table(gp002,index = ['class05','code'],aggfunc = sum)

KeyError: "None of [Index(['类别', '货号', '品名', '含量', '月初', '上日', '本日入库', '入库累计', '本日出库', '出库累计',\n       '结余'],\n      dtype='object')] are in the [columns]"