In [5]:
'''
对T+CLOUD上的收发存汇总表进行二次开发，与公司以前的格式一致
'''
import os
import numpy as np
import easygui
import pandas as pd
import openpyxl

In [6]:
lst = [
'存货分类 (1级)',
 '存货分类 (2级)',
 '存货分类 (3级)',
 '存货分类 (4级)',
 '存货分类 (5级)',
 '存货编码',
 '存货',
 '存货代码',
  '数量(主单位)',
 '平均单价',
 '金额',
 '数量(辅单位)',
 '计量单位组合',
 '数量(主单位).1',
 '平均单价.1',
 '金额.1',
 '数量(辅单位).1',
 '计量单位组合.1',
 '数量(主单位).2',
 '平均单价.2',
 '金额.2',
 '数量(辅单位).2',
 '计量单位组合.2',
 '数量(主单位).3',
 '平均单价.3',
 '金额.3',
 '辅数量',
 '计量单位组合.3']

lst2 = [
'class01',
 'class02',
 'class03',
 'class04',
 'class05',
 'code',
 'stock',
 'content',
  'begin_ben',
 '平均单价',
 '金额',
 'begin_jian',
 '计量单位组合',
 'ruku_ben',
 '平均单价.1',
 '金额.1',
 'ruku_jian',
 '计量单位组合.1',
 'chuku_ben',
 '平均单价.2',
 '金额.2',
 'chuku_jian',
 '计量单位组合.2',
 'end_ben',
 '平均单价.3',
 '金额.3',
 'end_jian',
 '计量单位组合.3']

lst3 =  [
 'class02',
 'class05',
 'code',
 'stock',
 'content',
 'begin_jian',
 'ruku_jian',
 'chuku_jian',
 'end_jian',
]


fname = r"F:\a00nutstore\008\zw08\用友报价\产成品库存\收发存汇总表01.xlsx"

def chuli(fname):
    df =  pd.read_excel(fname,skiprows = 7)
    df = df.iloc[:,1:]
    df.columns = lst
    df.columns = lst2
    df['content'] = df['end_ben']/df['end_jian']
    df = df[df['class01'] != '制表人:']
    df = df[df['class01'] != '合计：']
    df = df[df['class01'].notnull()]
    df = df[lst3]
    return df
df1 = chuli(fname)
df1

,class02,class05,code,stock,content,begin_jian,ruku_jian,chuku_jian,end_jian
0,抄本,材料纸,DB501,单行材料纸,500.0,150.0,NaN,2.0,148.0
1,抄本,材料纸,FB503,方格材料纸,500.0,98.0,NaN,NaN,98.0
2,抄本,材料纸,J1601,简装双行材料纸,270.0,81.0,NaN,NaN,81.0
3,抄本,材料纸,J1602,简装单行材料纸,270.0,115.0,NaN,NaN,115.0
4,抄本,材料纸,J1603,简装方格材料纸,270.0,54.0,NaN,NaN,54.0
...,...,...,...,...,...,...,...,...,...
1526,账本,装订配件,L16KPP,16KPP账夹（立信孔）,260.0,20.0,NaN,NaN,20.0
1527,账本,装订配件,存料卡,48K存料卡,5400.0,52.0,NaN,NaN,52.0
1528,账本,装订配件,固定资产明细卡,30K固定资产明细卡,3000.0,16.0,NaN,NaN,16.0
1529,账本,装订配件,商品卡,48K商品卡,5400.0,21.0,NaN,NaN,21.0
1530,账本,装订配件,账钉,账钉,100.0,8.0,NaN,NaN,8.0

In [7]:
fname2 = r"F:\a00nutstore\008\zw08\用友报价\产成品库存\收发存汇总表02.xlsx"
df2 = chuli(fname2)
df2

,class02,class05,code,stock,content,begin_jian,ruku_jian,chuku_jian,end_jian
0,抄本,材料纸,DB501,单行材料纸,500.0,150.0,NaN,2.0,148.0
1,抄本,材料纸,FB503,方格材料纸,500.0,98.0,NaN,NaN,98.0
2,抄本,材料纸,J1601,简装双行材料纸,270.0,81.0,NaN,NaN,81.0
3,抄本,材料纸,J1602,简装单行材料纸,270.0,115.0,NaN,NaN,115.0
4,抄本,材料纸,J1603,简装方格材料纸,270.0,54.0,NaN,NaN,54.0
...,...,...,...,...,...,...,...,...,...
1526,账本,装订配件,L16KPP,16KPP账夹（立信孔）,260.0,20.0,NaN,NaN,20.0
1527,账本,装订配件,存料卡,48K存料卡,5400.0,52.0,NaN,NaN,52.0
1528,账本,装订配件,固定资产明细卡,30K固定资产明细卡,3000.0,16.0,NaN,NaN,16.0
1529,账本,装订配件,商品卡,48K商品卡,5400.0,21.0,NaN,NaN,21.0
1530,账本,装订配件,账钉,账钉,100.0,8.0,NaN,NaN,8.0

In [12]:
lst01_yesterday =  [
 'class02',
 'class05',
 'code',
 'stock',
 'begin_jian',
 'ruku_jian',
 'chuku_jian',
]
lst02_yesterday =  [
 'class02',
 'class05',
 'code',
 'stock',
 'yesterday_jian',
 'yesterday_ruku',
 'yesterday_chuku',

]
df1 = df1[lst01_yesterday]
df1.columns = lst02_yesterday
df1

,class02,class05,code,stock,yesterday_jian,yesterday_ruku,yesterday_chuku
0,抄本,材料纸,DB501,单行材料纸,150.0,NaN,2.0
1,抄本,材料纸,FB503,方格材料纸,98.0,NaN,NaN
2,抄本,材料纸,J1601,简装双行材料纸,81.0,NaN,NaN
3,抄本,材料纸,J1602,简装单行材料纸,115.0,NaN,NaN
4,抄本,材料纸,J1603,简装方格材料纸,54.0,NaN,NaN
...,...,...,...,...,...,...,...
1526,账本,装订配件,L16KPP,16KPP账夹（立信孔）,20.0,NaN,NaN
1527,账本,装订配件,存料卡,48K存料卡,52.0,NaN,NaN
1528,账本,装订配件,固定资产明细卡,30K固定资产明细卡,16.0,NaN,NaN
1529,账本,装订配件,商品卡,48K商品卡,21.0,NaN,NaN
1530,账本,装订配件,账钉,账钉,8.0,NaN,NaN

In [8]:
merge = pd.merge(df2,df1,how = 'left',on = ['class02','class05','code','stock']) 
merge

,class02,class05,code,stock,content_x,begin_jian_x,ruku_jian_x,chuku_jian_x,end_jian_x,content_y,begin_jian_y,ruku_jian_y,chuku_jian_y,end_jian_y
0,抄本,材料纸,DB501,单行材料纸,500.0,150.0,NaN,2.0,148.0,500.0,150.0,NaN,2.0,148.0
1,抄本,材料纸,FB503,方格材料纸,500.0,98.0,NaN,NaN,98.0,500.0,98.0,NaN,NaN,98.0
2,抄本,材料纸,J1601,简装双行材料纸,270.0,81.0,NaN,NaN,81.0,270.0,81.0,NaN,NaN,81.0
3,抄本,材料纸,J1602,简装单行材料纸,270.0,115.0,NaN,NaN,115.0,270.0,115.0,NaN,NaN,115.0
4,抄本,材料纸,J1603,简装方格材料纸,270.0,54.0,NaN,NaN,54.0,270.0,54.0,NaN,NaN,54.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1526,账本,装订配件,L16KPP,16KPP账夹（立信孔）,260.0,20.0,NaN,NaN,20.0,260.0,20.0,NaN,NaN,20.0
1527,账本,装订配件,存料卡,48K存料卡,5400.0,52.0,NaN,NaN,52.0,5400.0,52.0,NaN,NaN,52.0
1528,账本,装订配件,固定资产明细卡,30K固定资产明细卡,3000.0,16.0,NaN,NaN,16.0,3000.0,16.0,NaN,NaN,16.0
1529,账本,装订配件,商品卡,48K商品卡,5400.0,21.0,NaN,NaN,21.0,5400.0,21.0,NaN,NaN,21.0
1530,账本,装订配件,账钉,账钉,100.0,8.0,NaN,NaN,8.0,100.0,8.0,NaN,NaN,8.0

In [9]:
lst_merge = ['class02','class05','code','stock',
             'content',
             'begin_jian','yesterday_jian',
             'yesterday_ruku','ruku_jian',
              'yesterday_chuku','chuku_jian',
               'end_jian']
merge = merge[lst_merge]
merge

KeyError: "['content', 'begin_jian', 'yesterday_jian', 'yesterday_ruku', 'ruku_jian', 'yesterday_chuku', 'chuku_jian', 'end_jian'] not in index"

In [9]:
merge.to_excel('收发存汇总表0718.xlsx',index = False)

C:\Users\redda\AppData\Local\Temp\ipykernel_19612\1957244528.py:1: UserWarning: Pandas requires version '3.0.5' or newer of 'xlsxwriter' (version '3.0.3' currently installed).
  merge.to_excel('收发存汇总表0718.xlsx',index = False)

In [4]:
merge1 = merge.copy()
merge1

NameError: name 'merge' is not defined

In [3]:
merge1

NameError: name 'merge1' is not defined

In [2]:
gp = merge1.groupby('class02')
gp

NameError: name 'merge1' is not defined

In [1]:
for name,group in gp:
    gp2 = gp.groupby('class05')
    table = pd.pivot_table(gp2,index = ['class05','code'],aggfunc = sum)
    gp3 = table.groupby('class05')
    for k,d in gp3:
        print(k,d)

NameError: name 'gp' is not defined

In [ ]:
df.to_excel(writer, sheet_name='加工', index=False)
beihuo.to_excel(writer, sheet_name='备货', index=False)
df1.to_excel(writer, sheet_name='本数', index=False)

In [73]:
# 根据Category进行分组并计算总和
grouped = merge.groupby('class02')
 
# 创建一个字典，用于存储每个分组的数据
group_to_excel = {}
 
# 遍历分组并将结果存入字典
for name, group in grouped:
    group_to_excel[name] = group
 
# 分别将不同分组保存到Excel文件
for name, group in group_to_excel.items():
    group.to_excel(f'{name}_output.xlsx', index=False)

C:\Users\redda\AppData\Local\Temp\ipykernel_32444\4258439903.py:13: UserWarning: Pandas requires version '3.0.5' or newer of 'xlsxwriter' (version '3.0.3' currently installed).
  group.to_excel(f'{name}_output.xlsx', index=False)

In [17]:
df_fyz = c.reset_index()
df_fyz

KeyError: 'Column not found: 复印纸'

In [18]:
for name,sheet in gp:
    print(name,sheet)

复印纸     class02  class05      code          stock  content  begin_jian  \
818     复印纸  莱特全木浆系列  A470克复印纸  A470克全木浆中性复印纸      8.0       118.0
819     复印纸  莱特全木浆系列  A480克复印纸  A480克全木浆中性复印纸      8.0        26.0

     yesterday_jian  yesterday_ruku  ruku_jian  yesterday_chuku  chuku_jian  \
818           118.0             NaN        NaN              NaN         NaN
819            26.0             NaN        NaN              NaN         NaN

     end_jian
818     118.0
819      26.0
抄本     class02 class05   code           stock  content  begin_jian  \
0        抄本     材料纸  DB501           单行材料纸    500.0       150.0
1        抄本     材料纸  FB503           方格材料纸    500.0        98.0
2        抄本     材料纸  J1601         简装双行材料纸    270.0        81.0
3        抄本     材料纸  J1602         简装单行材料纸    270.0       115.0
4        抄本     材料纸  J1603         简装方格材料纸    270.0        54.0
..      ...     ...    ...             ...      ...         ...
588      抄本    卡通硬抄  N0663    D32K96P卡通硬面抄    108.0       102.0
589      抄本    卡通硬抄  N0664   D32K128P卡通硬面抄     84.0        48.0
590      抄本    卡通硬抄  N0667     36K64P卡通硬面抄    140.0         4.0
591      抄本    卡通硬抄  N0668  36K64P卡通硬面学生日记    140.0        70.0
592      抄本    卡通硬抄  N0669   D32K64P硬面学生日记    144.0        72.0

     yesterday_jian  yesterday_ruku  ruku_jian  yesterday_chuku  chuku_jian  \
0             150.0             NaN        NaN              2.0         2.0
1              98.0             NaN        NaN              NaN         NaN
2              81.0             NaN        NaN              NaN         NaN
3             115.0             NaN        NaN              NaN         NaN
4              54.0             NaN        NaN              NaN         NaN
..              ...             ...        ...              ...         ...
588           102.0             NaN        NaN              NaN         NaN
589            48.0             NaN        NaN              NaN         NaN
590             4.0             NaN        NaN              NaN         NaN
591            70.0             NaN        NaN              NaN         NaN
592            72.0             NaN        NaN              NaN         NaN

     end_jian
0       148.0
1        98.0
2        81.0
3       115.0
4        54.0
..        ...
588     102.0
589      48.0
590       4.0
591      70.0
592      72.0

[593 rows x 12 columns]
新锐      class02 class05           code             stock     content  begin_jian  \
1203      新锐  新锐处理产品     RZW-1660混装       16K60型卡面作文本  200.000000        1.00
1204      新锐    新锐订制  RFDF1660N原木定制     16K60型牛卡缝线大方格  200.000000        0.50
1205      新锐    新锐订制  RFPY3260N原木定制     32K60型牛卡缝线拼音簿  307.692308        0.13
1206      新锐    新锐订制  RFSX3260N原木定制     32K60型牛卡缝线数学本  320.754717        0.53
1207      新锐    新锐订制   RFY1660N原木定制     16K60型牛卡缝线英语本  200.000000        0.05
...      ...     ...            ...               ...         ...         ...
1346      新锐    新锐软抄      RY-1660NZ  16K60型牛卡英语簿B6602  200.000000       17.00
1347      新锐    新锐软抄       RY-32150      32K150型卡面英语本  240.000000       23.00
1348      新锐    新锐软抄       RZW-1660       16K60型卡面作文本  200.000000        1.00
1349      新锐    新锐软抄     RZW-1660NZ  16K60型牛卡作文簿B6603  200.000000       36.00
1350      新锐    新锐软抄     RZW-1680NZ  16K80型牛卡作文簿B6803  140.000000       42.00

      yesterday_jian  yesterday_ruku  ruku_jian  yesterday_chuku  chuku_jian  \
1203            1.00             NaN        NaN              NaN         NaN
1204            0.50             NaN        NaN              NaN         NaN
1205            0.13             NaN        NaN              NaN         NaN
1206            0.53             NaN        NaN              NaN         NaN
1207            0.05             NaN        NaN              NaN         NaN
...              ...             ...        ...              ...         ...
1346           17.00             NaN        NaN              NaN         NaN
1347           23.00             NaN        NaN              NaN         NaN
1348            1.00             NaN        NaN              NaN         NaN
1349           36.00             NaN        NaN              NaN         NaN
1350           42.00             NaN        NaN              NaN         NaN

      end_jian
1203      1.00
1204      0.50
1205      0.13
1206      0.53
1207      0.05
...        ...
1346     17.00
1347     23.00
1348      1.00
1349     36.00
1350     42.00

[148 rows x 12 columns]
电商     class02 class05         code               stock     content  begin_jian  \
593      电商     备课本   16K备课本-30P          16K备课本-30P  240.000000       88.00
594      电商     备课本  16K备课本-50Pa         16K备课本-50Pa  180.000000      114.00
595      电商  18K胶装本     HWC1840N     18K40型牛皮无线胶装语文本  280.000000       70.00
596      电商  18K胶装本    HWHP1840N    18K40型牛皮无线胶装汉语拼音  280.000000       47.00
597      电商  18K胶装本    HWLZ1840N     18K40型牛皮无线胶装练字本  280.000000       51.00
..      ...     ...          ...                 ...         ...         ...
813      电商   牛卡线环本   EXLA6100NB  A6-100型牛卡线环横线本（上翻）  224.004379       73.07
814      电商   牛卡线环本   EXLB5100NB  B5-100型牛卡线环横线本（上翻）   95.995501       88.90
815      电商   牛卡线环本  EXWGA5100NB  A5-100型牛卡线环网格本（上翻）  111.989039       43.79
816      电商   牛卡线环本  EXWGA6100NB  A6-100型牛卡线环网格本（上翻）  224.021352       44.96
817      电商   牛卡线环本  EXWGB5100NB  B5-100型牛卡线环网格本（上翻）   95.994832       30.96

     yesterday_jian  yesterday_ruku  ruku_jian  yesterday_chuku  chuku_jian  \
593           88.00             NaN        NaN              NaN         NaN
594          114.00             NaN        NaN              NaN         NaN
595           70.00             NaN        NaN              NaN         NaN
596           47.00             NaN        NaN              NaN         NaN
597           51.00             NaN        NaN              NaN         NaN
..              ...             ...        ...              ...         ...
813           73.07             NaN        NaN              NaN         NaN
814           88.90             NaN        NaN              NaN         NaN
815           43.79             NaN        NaN              NaN         NaN
816           44.96             NaN        NaN              NaN         NaN
817           30.96             NaN        NaN              NaN         NaN

     end_jian
593     88.00
594    114.00
595     70.00
596     47.00
597     51.00
..        ...
813     73.07
814     88.90
815     43.79
816     44.96
817     30.96

[225 rows x 12 columns]
账本      class02 class05     code         stock  content  begin_jian  \
1351      账本      报表     7001       8K现金流量表    110.0        28.0
1352      账本      报表     7002        16K万用表    220.0         9.0
1353      账本      报表     7003         8K万用表    110.0        53.0
1354      账本      报表     7005    16K工资表（横式）    220.0        28.0
1355      账本      报表     7007  16K盘存报告表(横式)    220.0        11.0
...      ...     ...      ...           ...      ...         ...
1526      账本    装订配件   L16KPP  16KPP账夹（立信孔）    260.0        20.0
1527      账本    装订配件      存料卡        48K存料卡   5400.0        52.0
1528      账本    装订配件  固定资产明细卡    30K固定资产明细卡   3000.0        16.0
1529      账本    装订配件      商品卡        48K商品卡   5400.0        21.0
1530      账本    装订配件       账钉            账钉    100.0         8.0

      yesterday_jian  yesterday_ruku  ruku_jian  yesterday_chuku  chuku_jian  \
1351            28.0             NaN        NaN              NaN         NaN
1352             9.0             NaN        NaN              NaN         NaN
1353            53.0             NaN        NaN              NaN         NaN
1354            28.0             NaN        NaN              NaN         NaN
1355            11.0             NaN        NaN              NaN         NaN
...              ...             ...        ...              ...         ...
1526            20.0             NaN        NaN              NaN         NaN
1527            52.0             NaN        NaN              NaN         NaN
1528            16.0             NaN        NaN              NaN         NaN
1529            21.0             NaN        NaN              NaN         NaN
1530             8.0             NaN        NaN              NaN         NaN

      end_jian
1351      28.0
1352       9.0
1353      53.0
1354      28.0
1355      11.0
...        ...
1526      20.0
1527      52.0
1528      16.0
1529      21.0
1530       8.0

[180 rows x 12 columns]
锐意      class02    class05         code               stock  content  begin_jian  \
820       锐意  锐意PP缝线活页夹      PJC1660       16K60型PP缝线纠错本    160.0         1.0
821       锐意     锐意处理产品  DL-16150混装a     16K150型精品道林卡面软抄     60.0         1.0
822       锐意     锐意处理产品   DL-1680混装a      16K80型精品道林卡面软抄    100.0         8.0
823       锐意     锐意处理产品   DY-3280混装a      32K80精品道林卡面英语本    200.0         1.0
824       锐意     锐意处理产品     FDS3260a  32K60型精品缝线读书笔记本40P    280.0        32.0
...      ...        ...          ...                 ...      ...         ...
1198      锐意       锐意线环   DX100-一间小店      100K盒装线环本C2403    480.0        49.0
1199      锐意       锐意线环   DX100-有一束光      100K盒装线环本A2302    480.0        14.0
1200      锐意       锐意线环    DXA5100混装           DXA5100混装     96.0        16.0
1201      锐意       锐意线环    DXA6100混装      A6100型精品双卡面线环本    192.0        35.0
1202      锐意       锐意线环    DXA7100混装      A7100型精品双卡面线环本    240.0        20.0

      yesterday_jian  yesterday_ruku  ruku_jian  yesterday_chuku  chuku_jian  \
820              1.0             NaN        NaN              NaN         NaN
821              1.0             NaN        NaN              NaN         NaN
822              8.0             NaN        NaN              NaN         NaN
823              1.0             NaN        NaN              NaN         NaN
824             32.0             NaN        NaN              NaN         NaN
...              ...             ...        ...              ...         ...
1198            49.0             NaN        NaN              NaN         NaN
1199            14.0             NaN        NaN              NaN         NaN
1200            16.0             NaN        NaN              NaN         NaN
1201            35.0             NaN        NaN              NaN         NaN
1202            20.0             NaN        NaN              NaN         NaN

      end_jian
820        1.0
821        1.0
822        8.0
823        1.0
824       32.0
...        ...
1198      49.0
1199      14.0
1200      16.0
1201      35.0
1202      20.0

[383 rows x 12 columns]

In [50]:
df_caoben =  gp.get_group('抄本')
df_caoben

,class02,class05,code,stock,content,begin_jian,yesterday_jian,yesterday_ruku,ruku_jian,yesterday_chuku,chuku_jian,end_jian
0,抄本,材料纸,DB501,单行材料纸,500.0,150.0,150.0,NaN,NaN,2.0,2.0,148.0
1,抄本,材料纸,FB503,方格材料纸,500.0,98.0,98.0,NaN,NaN,NaN,NaN,98.0
2,抄本,材料纸,J1601,简装双行材料纸,270.0,81.0,81.0,NaN,NaN,NaN,NaN,81.0
3,抄本,材料纸,J1602,简装单行材料纸,270.0,115.0,115.0,NaN,NaN,NaN,NaN,115.0
4,抄本,材料纸,J1603,简装方格材料纸,270.0,54.0,54.0,NaN,NaN,NaN,NaN,54.0
...,...,...,...,...,...,...,...,...,...,...,...,...
588,抄本,卡通硬抄,N0663,D32K96P卡通硬面抄,108.0,102.0,102.0,NaN,NaN,NaN,NaN,102.0
589,抄本,卡通硬抄,N0664,D32K128P卡通硬面抄,84.0,48.0,48.0,NaN,NaN,NaN,NaN,48.0
590,抄本,卡通硬抄,N0667,36K64P卡通硬面抄,140.0,4.0,4.0,NaN,NaN,NaN,NaN,4.0
591,抄本,卡通硬抄,N0668,36K64P卡通硬面学生日记,140.0,70.0,70.0,NaN,NaN,NaN,NaN,70.0
592,抄本,卡通硬抄,N0669,D32K64P硬面学生日记,144.0,72.0,72.0,NaN,NaN,NaN,NaN,72.0

In [23]:
df_caoben = df_caoben.set_index('class02')
df_caoben

,class05,code,stock,content,begin_jian,yesterday_jian,yesterday_ruku,ruku_jian,yesterday_chuku,chuku_jian,end_jian
class02,,,,,,,,,,,
抄本,材料纸,DB501,单行材料纸,500.0,150.0,150.0,NaN,NaN,2.0,2.0,148.0
抄本,材料纸,FB503,方格材料纸,500.0,98.0,98.0,NaN,NaN,NaN,NaN,98.0
抄本,材料纸,J1601,简装双行材料纸,270.0,81.0,81.0,NaN,NaN,NaN,NaN,81.0
抄本,材料纸,J1602,简装单行材料纸,270.0,115.0,115.0,NaN,NaN,NaN,NaN,115.0
抄本,材料纸,J1603,简装方格材料纸,270.0,54.0,54.0,NaN,NaN,NaN,NaN,54.0
...,...,...,...,...,...,...,...,...,...,...,...
抄本,卡通硬抄,N0663,D32K96P卡通硬面抄,108.0,102.0,102.0,NaN,NaN,NaN,NaN,102.0
抄本,卡通硬抄,N0664,D32K128P卡通硬面抄,84.0,48.0,48.0,NaN,NaN,NaN,NaN,48.0
抄本,卡通硬抄,N0667,36K64P卡通硬面抄,140.0,4.0,4.0,NaN,NaN,NaN,NaN,4.0
抄本,卡通硬抄,N0668,36K64P卡通硬面学生日记,140.0,70.0,70.0,NaN,NaN,NaN,NaN,70.0
抄本,卡通硬抄,N0669,D32K64P硬面学生日记,144.0,72.0,72.0,NaN,NaN,NaN,NaN,72.0

In [74]:
df_caoben1 =  df_caoben.copy()
gp_caoben = df_caoben1.groupby('class05')

In [52]:
gp_caoben.sum()

,class02,code,stock,content,begin_jian,yesterday_jian,yesterday_ruku,ruku_jian,yesterday_chuku,chuku_jian,end_jian
class05,,,,,,,,,,,
云南版小学生本,抄本抄本抄本抄本抄本抄本抄本抄本,YN104YN106YN107YN201YN302YN304YN306YN307,汉语拼音本语文练习本作文本英语练习本作文本英语作业本代数作业本物理作业本,8385.848634,3.92,3.92,0.0,0.0,0.0,0.0,3.92
办公硬抄,抄本抄本抄本抄本抄本,N0651N0653N0654N0709N0767,D32K64P办公硬面抄D32K96P办公硬面抄D32K128P办公硬面抄B580P精品办公...,468.000000,239.00,239.00,0.0,0.0,0.0,0.0,239.00
华北版小学生本,抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本,HB101CHB103HB103CHB104CHB105CHB106CHB107CHB108...,田字格本拼音本拼音本拼音练习本多格算术本方格算术本生字本方格本方格本条格本语文本英语本数学本...,15046.465948,1360.29,1360.29,0.0,0.0,0.0,0.0,1360.29
华阳版小学生本,抄本抄本抄本抄本抄本抄本,HY101HY102HY107HY111HY113HY117,24K拼音写字簿24K单行簿24K汉语拼音簿24K田字簿24K中方格簿24K中横格簿,5760.000000,66.00,66.00,0.0,0.0,0.0,0.0,66.00
卡通硬抄,抄本抄本抄本抄本抄本抄本抄本抄本,N0541N0661N0662N0663N0664N0667N0668N0669,牛皮语文本D32K64P卡面硬面抄D32K80P卡面硬面抄D32K96P卡通硬面抄D32K1...,1200.000000,488.00,488.00,0.0,0.0,0.0,0.0,488.00
唐山版小学生本,抄本抄本抄本抄本抄本,TS102ZTS103ZTS301ZTS302ZTS303Z,32K注音本32K横格本16K备课本16K数学本16K英语本,1400.000000,747.70,747.70,0.0,0.0,0.0,0.0,747.70
外贸订制品,抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本...,A1-052399A1-052400A1-052402A1-052403A1-054197E...,A1-052399A1-052400A1-052402A1-052403A1-054197E...,1342.000000,2232.00,2232.00,0.0,0.0,0.0,0.0,2232.00
天津东丽津南区小字本,抄本抄本,HD201aHD203a,作业本-1（汉语拼音）作业本-3,979.959920,20.00,20.00,0.0,0.0,0.0,0.0,20.00
天津南开西青区小字本,抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本...,NK101NK102NK103NK104NK105NK106NK107NK109-4NK20...,汉语拼音作业本（1号）作业本（2号）作业本（3号）竖式计算作业本横式计算作业本（8号）英语本...,33568.875811,5660.55,5660.55,0.0,0.0,0.0,0.0,5660.55
太原版小学生本,抄本抄本抄本抄本抄本,TY201TY203TY204TY205TY208,作业本数学本作文本（横翻）英语本（横翻）语文本,2000.000000,6.00,6.00,0.0,0.0,0.0,0.0,6.00
山东版小学生本,抄本抄本抄本抄本抄本抄本抄本抄本抄本,BH101ZBH102ZBH103ZBH105Z（9格）BH106Z（9格）BH201ZBH...,32K小演草32K英语练习本32K笔记本32K拼音田字格（9格）32K田字格（9格）16K大...,4840.000000,114.00,114.00,0.0,0.0,0.0,0.0,114.00
广州版小学生本,抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本,GZ101GZ101混装GZ102GZ103GZ104GZ105GZ106GZ107竖GZ1...,32K拼音写字簿GZ101混装32K单行簿32K英语簿32K大方格簿32K图画簿32K课文簿...,21992.589258,925.99,925.99,0.0,0.0,0.0,0.0,925.99
成都版小学生本,抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本,CD101NHCD102NHCD103NHCD104NHCD105NHCD106NHCD10...,32K小字本32K数学本32K习字本32K拼习本32K拼音本32K英语本32K作业本18K作...,7860.000000,1410.00,1410.00,0.0,0.0,0.0,0.0,1410.00
抄本处理产品,抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本,1508废次品16K废次品32K废次品HY602混装aN0424废次品N0576废次品N05...,1508废次品16K废次品32K废次品HY602混装N0424废次品N0576废次品N057...,2840.000000,664.00,664.00,0.0,0.0,0.0,0.0,664.00
拍纸簿,抄本,N0007,130K卡面便签本,300.000000,149.00,149.00,0.0,0.0,0.0,0.0,149.00
新疆版小学生本,抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本...,XJ102XJ103XJ104XJ106XJ201XJ202XJ204XJ205XJ206X...,32K方格本32K算术本32K拼音本32K图画本24K英语本24K作业本24K数学本24K双...,19560.017593,2713.21,2713.21,0.0,0.0,12.0,12.0,2701.21
昆明版小学生本,抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本...,KM101KM101混装KM102KM103KM103NKM103ZKM104KM104NK...,32K大楷本KM101混装32K中楷本32K小楷本32K小楷本32K小楷本32K汉语拼音汉字...,24512.161225,512.17,512.17,0.0,0.0,0.0,0.0,512.17
材料纸,抄本抄本抄本抄本抄本抄本抄本抄本,DB501FB503J1601J1602J1603MB504SB502TB505,单行材料纸方格材料纸简装双行材料纸简装单行材料纸简装方格材料纸米字材料纸双行材料纸田字材料纸,3310.000000,788.00,788.00,0.0,0.0,2.0,2.0,786.00
杭州科兴小学生本,抄本抄本抄本抄本抄本抄本抄本抄本,HZ101HZ102HZ103HZ104HZ105HZ106HZ107HZ302,写字簿田字簿语文簿算术簿拼音簿方格簿数学簿写字本,4730.000000,190.00,190.00,0.0,0.0,0.0,0.0,190.00
汉办版小学生本,抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本...,401401F401Z402402Z404404F404Z406406F406Z407横40...,32K拼音本32K拼音本拼音本32K横式语文本语文本32K算术本32K算术本算术本低算本32...,31279.969597,2527.97,2527.97,0.0,0.0,17.0,17.0,2510.97
汉正街热脉小学生本,抄本抄本抄本抄本抄本抄本抄本,RM406RM602RM603RM604RM605RM606RM609,低算本语文本作文本算术本练习本英语本小字本,3820.000000,208.00,208.00,0.0,0.0,0.0,0.0,208.00
练字本,抄本抄本抄本抄本,J1605J1606J1607J1608,16K练字本(田字格)16K练字本(米字格)16K练字本(红方格)16K草稿本,1280.000000,253.00,253.00,0.0,0.0,2.0,2.0,251.00
胶印软抄,抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本...,N0002N0003N0422N0423N0424N0425N0430N0516办N0517...,A6软面工作手册36K软面工作手册32K60型办公无线胶订本32K80型办公无线胶订本32K...,9299.986626,12273.03,12212.03,0.0,0.0,4.0,65.0,12208.03
胶印软抄.,抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本...,N0311N0321N0331N0332N0341N0342N0511N0521N0531N...,B540型卡面卡通软抄B540型卡面卡通英语本B540型卡面卡通作文本B560型卡面卡通作文...,9680.000000,2207.00,2197.00,0.0,0.0,0.0,10.0,2197.00
西北版小学生本,抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本,XA101XA102XA103XA104XA105XA106XA201XA202XA203X...,32K生字本32K算术本32K拼音本32K写话本32K英语本32K美术本16K作文本16K作...,5320.151828,769.34,769.34,0.0,0.0,0.0,0.0,769.34
订制产品,抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本...,16K30页牛皮草稿本湖南16K50页牛皮草稿本湖南A4单线信纸A4双线信纸A4图画本（混版...,16K30页牛皮草稿本湖南16K50页牛皮草稿本湖南A4单线信纸A4双线信纸A4图画本（混版...,33291.431725,15004.00,14867.00,0.0,0.0,0.0,137.0,14867.00
贵州版小学生本,抄本抄本抄本抄本抄本抄本抄本抄本,24K大横格本(贵州)24K单行本（贵州）a24K课文簿(贵州)24K拼音写字簿(贵州)24...,24K大横格本(贵州)24K单行本(贵州)24K课文簿(贵州)24K拼音写字簿(贵州)24K...,7360.000000,147.00,147.00,0.0,0.0,0.0,0.0,147.00
重庆版小学生本,抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本抄本,CQ103CQ103aCQ105aCQ105NbCQ106CQ108CQ108aCQ201C...,32K习字本32K习字本32K拼习本32K牛皮拼习本32K小字本32K数学本32K数学本24...,6960.000000,228.60,228.60,0.0,0.0,0.0,0.0,228.60
长沙版小学生本,抄本抄本抄本抄本抄本抄本,CS101CS102CS105CS107CS108CS110,32K生字本32K田字本32K拼音本32K作文本32K数学本32K语文练习本,7199.438202,428.12,428.12,0.0,0.0,1.0,1.0,427.12

In [26]:
df_caoben

,class05,code,stock,content,begin_jian,yesterday_jian,yesterday_ruku,ruku_jian,yesterday_chuku,chuku_jian,end_jian
class02,,,,,,,,,,,
抄本,材料纸,DB501,单行材料纸,500.0,150.0,150.0,NaN,NaN,2.0,2.0,148.0
抄本,材料纸,FB503,方格材料纸,500.0,98.0,98.0,NaN,NaN,NaN,NaN,98.0
抄本,材料纸,J1601,简装双行材料纸,270.0,81.0,81.0,NaN,NaN,NaN,NaN,81.0
抄本,材料纸,J1602,简装单行材料纸,270.0,115.0,115.0,NaN,NaN,NaN,NaN,115.0
抄本,材料纸,J1603,简装方格材料纸,270.0,54.0,54.0,NaN,NaN,NaN,NaN,54.0
...,...,...,...,...,...,...,...,...,...,...,...
抄本,卡通硬抄,N0663,D32K96P卡通硬面抄,108.0,102.0,102.0,NaN,NaN,NaN,NaN,102.0
抄本,卡通硬抄,N0664,D32K128P卡通硬面抄,84.0,48.0,48.0,NaN,NaN,NaN,NaN,48.0
抄本,卡通硬抄,N0667,36K64P卡通硬面抄,140.0,4.0,4.0,NaN,NaN,NaN,NaN,4.0
抄本,卡通硬抄,N0668,36K64P卡通硬面学生日记,140.0,70.0,70.0,NaN,NaN,NaN,NaN,70.0
抄本,卡通硬抄,N0669,D32K64P硬面学生日记,144.0,72.0,72.0,NaN,NaN,NaN,NaN,72.0

In [29]:
table = pd.pivot_table(df_caoben, index=['class02', 'class05', 'code','stock','content'], aggfunc='sum')
table

                                            begin_jian  chuku_jian  end_jian  \
class02 class05 code  stock    content
抄本      云南版小学生本 YN104 汉语拼音本    1428.571429        0.07         0.0      0.07
                YN106 语文练习本    1402.298851        0.87         0.0      0.87
                YN107 作文本      1402.597403        0.77         0.0      0.77
                YN201 英语练习本    952.380952         0.21         0.0      0.21
                YN302 作文本      800.000000         1.25         0.0      1.25
...                                                ...         ...       ...
        长沙版小学生本 CS102 32K田字本   1199.438202        7.12         0.0      7.12
                CS105 32K拼音本   1200.000000       64.00         0.0     64.00
                CS107 32K作文本   1200.000000      136.00         0.0    136.00
                CS108 32K数学本   1200.000000      142.00         1.0    141.00
                CS110 32K语文练习本 1200.000000       12.00         0.0     12.00

                                            ruku_jian  yesterday_chuku  \
class02 class05 code  stock    content
抄本      云南版小学生本 YN104 汉语拼音本    1428.571429        0.0              0.0
                YN106 语文练习本    1402.298851        0.0              0.0
                YN107 作文本      1402.597403        0.0              0.0
                YN201 英语练习本    952.380952         0.0              0.0
                YN302 作文本      800.000000         0.0              0.0
...                                               ...              ...
        长沙版小学生本 CS102 32K田字本   1199.438202        0.0              0.0
                CS105 32K拼音本   1200.000000        0.0              0.0
                CS107 32K作文本   1200.000000        0.0              0.0
                CS108 32K数学本   1200.000000        0.0              1.0
                CS110 32K语文练习本 1200.000000        0.0              0.0

                                            yesterday_jian  yesterday_ruku
class02 class05 code  stock    content
抄本      云南版小学生本 YN104 汉语拼音本    1428.571429            0.07             0.0
                YN106 语文练习本    1402.298851            0.87             0.0
                YN107 作文本      1402.597403            0.77             0.0
                YN201 英语练习本    952.380952             0.21             0.0
                YN302 作文本      800.000000             1.25             0.0
...                                                    ...             ...
        长沙版小学生本 CS102 32K田字本   1199.438202            7.12             0.0
                CS105 32K拼音本   1200.000000           64.00             0.0
                CS107 32K作文本   1200.000000          136.00             0.0
                CS108 32K数学本   1200.000000          142.00             0.0
                CS110 32K语文练习本 1200.000000           12.00             0.0

[592 rows x 7 columns]

In [32]:
df_caoben1 = df_caoben.copy()
df_caoben1 = df_caoben1.set_index('class02')
df_caoben1

,class05,code,stock,content,begin_jian,yesterday_jian,yesterday_ruku,ruku_jian,yesterday_chuku,chuku_jian,end_jian
class02,,,,,,,,,,,
抄本,材料纸,DB501,单行材料纸,500.0,150.0,150.0,NaN,NaN,2.0,2.0,148.0
抄本,材料纸,FB503,方格材料纸,500.0,98.0,98.0,NaN,NaN,NaN,NaN,98.0
抄本,材料纸,J1601,简装双行材料纸,270.0,81.0,81.0,NaN,NaN,NaN,NaN,81.0
抄本,材料纸,J1602,简装单行材料纸,270.0,115.0,115.0,NaN,NaN,NaN,NaN,115.0
抄本,材料纸,J1603,简装方格材料纸,270.0,54.0,54.0,NaN,NaN,NaN,NaN,54.0
...,...,...,...,...,...,...,...,...,...,...,...
抄本,卡通硬抄,N0663,D32K96P卡通硬面抄,108.0,102.0,102.0,NaN,NaN,NaN,NaN,102.0
抄本,卡通硬抄,N0664,D32K128P卡通硬面抄,84.0,48.0,48.0,NaN,NaN,NaN,NaN,48.0
抄本,卡通硬抄,N0667,36K64P卡通硬面抄,140.0,4.0,4.0,NaN,NaN,NaN,NaN,4.0
抄本,卡通硬抄,N0668,36K64P卡通硬面学生日记,140.0,70.0,70.0,NaN,NaN,NaN,NaN,70.0
抄本,卡通硬抄,N0669,D32K64P硬面学生日记,144.0,72.0,72.0,NaN,NaN,NaN,NaN,72.0

In [53]:
df_caoben2 = df_caoben.iloc[:,1:]
table = pd.pivot_table(df_caoben1,index = ['class05','code'],aggfunc = sum)

C:\Users\redda\AppData\Local\Temp\ipykernel_32444\1607342732.py:2: FutureWarning: The provided callable <built-in function sum> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  table = pd.pivot_table(df_caoben1,index = ['class05','code'],aggfunc = sum)

In [54]:
table

               begin_jian  chuku_jian class02      content  end_jian  \
class05 code
云南版小学生本 YN104        0.07         0.0      抄本  1428.571429      0.07
        YN106        0.87         0.0      抄本  1402.298851      0.87
        YN107        0.77         0.0      抄本  1402.597403      0.77
        YN201        0.21         0.0      抄本   952.380952      0.21
        YN302        1.25         0.0      抄本   800.000000      1.25
...                   ...         ...     ...          ...       ...
长沙版小学生本 CS102        7.12         0.0      抄本  1199.438202      7.12
        CS105       64.00         0.0      抄本  1200.000000     64.00
        CS107      136.00         0.0      抄本  1200.000000    136.00
        CS108      142.00         1.0      抄本  1200.000000    141.00
        CS110       12.00         0.0      抄本  1200.000000     12.00

               ruku_jian     stock  yesterday_chuku  yesterday_jian  \
class05 code
云南版小学生本 YN104        0.0     汉语拼音本              0.0            0.07
        YN106        0.0     语文练习本              0.0            0.87
        YN107        0.0       作文本              0.0            0.77
        YN201        0.0     英语练习本              0.0            0.21
        YN302        0.0       作文本              0.0            1.25
...                  ...       ...              ...             ...
长沙版小学生本 CS102        0.0    32K田字本              0.0            7.12
        CS105        0.0    32K拼音本              0.0           64.00
        CS107        0.0    32K作文本              0.0          136.00
        CS108        0.0    32K数学本              1.0          142.00
        CS110        0.0  32K语文练习本              0.0           12.00

               yesterday_ruku
class05 code
云南版小学生本 YN104             0.0
        YN106             0.0
        YN107             0.0
        YN201             0.0
        YN302             0.0
...                       ...
长沙版小学生本 CS102             0.0
        CS105             0.0
        CS107             0.0
        CS108             0.0
        CS110             0.0

[593 rows x 10 columns]

In [55]:
grouped = table.groupby('class05')
grouped
# data = []
# for k, d in grouped:
#     j = d.append(d.sum().rename((k, '', '')))    #关键操作，从百度上照搬！
#     datas.append(j)
# df_total = pd.concat(datas)
# df_total

In [56]:
grouped = table.groupby('class05')

In [61]:
d  = grouped.get_group('长沙版小学生本')
d

               begin_jian  chuku_jian class02      content  end_jian  \
class05 code
长沙版小学生本 CS101       67.00         0.0      抄本  1200.000000     67.00
        CS102        7.12         0.0      抄本  1199.438202      7.12
        CS105       64.00         0.0      抄本  1200.000000     64.00
        CS107      136.00         0.0      抄本  1200.000000    136.00
        CS108      142.00         1.0      抄本  1200.000000    141.00
        CS110       12.00         0.0      抄本  1200.000000     12.00

               ruku_jian     stock  yesterday_chuku  yesterday_jian  \
class05 code
长沙版小学生本 CS101        0.0    32K生字本              0.0           67.00
        CS102        0.0    32K田字本              0.0            7.12
        CS105        0.0    32K拼音本              0.0           64.00
        CS107        0.0    32K作文本              0.0          136.00
        CS108        0.0    32K数学本              1.0          142.00
        CS110        0.0  32K语文练习本              0.0           12.00

               yesterday_ruku
class05 code
长沙版小学生本 CS101             0.0
        CS102             0.0
        CS105             0.0
        CS107             0.0
        CS108             0.0
        CS110             0.0

In [58]:
d.sum()

begin_jian                                         428.12
chuku_jian                                            1.0
class02                                      抄本抄本抄本抄本抄本抄本
content                                       7199.438202
end_jian                                           427.12
ruku_jian                                             0.0
stock              32K生字本32K田字本32K拼音本32K作文本32K数学本32K语文练习本
yesterday_chuku                                       1.0
yesterday_jian                                     428.12
yesterday_ruku                                        0.0
dtype: object

In [71]:
d1 = pd.concat([d,d.sum()])
d

               begin_jian  chuku_jian       class02      content  end_jian  \
class05 code
长沙版小学生本 CS101       67.00         0.0            抄本  1200.000000     67.00
        CS102        7.12         0.0            抄本  1199.438202      7.12
        CS105       64.00         0.0            抄本  1200.000000     64.00
        CS107      136.00         0.0            抄本  1200.000000    136.00
        CS108      142.00         1.0            抄本  1200.000000    141.00
        CS110      428.12         1.0  抄本抄本抄本抄本抄本抄本  7199.438202    427.12

               ruku_jian                                   stock  \
class05 code
长沙版小学生本 CS101        0.0                                  32K生字本
        CS102        0.0                                  32K田字本
        CS105        0.0                                  32K拼音本
        CS107        0.0                                  32K作文本
        CS108        0.0                                  32K数学本
        CS110        0.0  32K生字本32K田字本32K拼音本32K作文本32K数学本32K语文练习本

               yesterday_chuku  yesterday_jian  yesterday_ruku
class05 code
长沙版小学生本 CS101              0.0           67.00             0.0
        CS102              0.0            7.12             0.0
        CS105              0.0           64.00             0.0
        CS107              0.0          136.00             0.0
        CS108              1.0          142.00             0.0
        CS110              1.0          428.12             0.0

In [70]:
d.append(d.sum())

AttributeError: 'DataFrame' object has no attribute 'append'

In [63]:
dontent_xiaoji = d.loc['长沙版小学生本小计']['content']
dontent_xiaoji = ''

d

KeyError: '长沙版小学生本小计'

In [46]:
d.iloc[-1].to_list()

[428.12, 1.0, 7199.438202247191, 427.12, 0.0, '', 1.0, 428.12, 0.0, '', '', '']

In [47]:
d.loc['长沙版小学生本小计']['content']

7199.438202247191

In [72]:
d.to_excel('111-1.xlsx')

C:\Users\redda\AppData\Local\Temp\ipykernel_32444\2451316617.py:1: UserWarning: Pandas requires version '3.0.5' or newer of 'xlsxwriter' (version '3.0.3' currently installed).
  d.to_excel('111-1.xlsx')

In [75]:
df_caoben

,class02,class05,code,stock,content,begin_jian,yesterday_jian,yesterday_ruku,ruku_jian,yesterday_chuku,chuku_jian,end_jian
0,抄本,材料纸,DB501,单行材料纸,500.0,150.0,150.0,NaN,NaN,2.0,2.0,148.0
1,抄本,材料纸,FB503,方格材料纸,500.0,98.0,98.0,NaN,NaN,NaN,NaN,98.0
2,抄本,材料纸,J1601,简装双行材料纸,270.0,81.0,81.0,NaN,NaN,NaN,NaN,81.0
3,抄本,材料纸,J1602,简装单行材料纸,270.0,115.0,115.0,NaN,NaN,NaN,NaN,115.0
4,抄本,材料纸,J1603,简装方格材料纸,270.0,54.0,54.0,NaN,NaN,NaN,NaN,54.0
...,...,...,...,...,...,...,...,...,...,...,...,...
588,抄本,卡通硬抄,N0663,D32K96P卡通硬面抄,108.0,102.0,102.0,NaN,NaN,NaN,NaN,102.0
589,抄本,卡通硬抄,N0664,D32K128P卡通硬面抄,84.0,48.0,48.0,NaN,NaN,NaN,NaN,48.0
590,抄本,卡通硬抄,N0667,36K64P卡通硬面抄,140.0,4.0,4.0,NaN,NaN,NaN,NaN,4.0
591,抄本,卡通硬抄,N0668,36K64P卡通硬面学生日记,140.0,70.0,70.0,NaN,NaN,NaN,NaN,70.0
592,抄本,卡通硬抄,N0669,D32K64P硬面学生日记,144.0,72.0,72.0,NaN,NaN,NaN,NaN,72.0

In [76]:
df_caoben1 = df_caoben.copy()
df_caoben1 = df_caoben1.iloc[:,1:]

In [77]:
df_caoben1

,class05,code,stock,content,begin_jian,yesterday_jian,yesterday_ruku,ruku_jian,yesterday_chuku,chuku_jian,end_jian
0,材料纸,DB501,单行材料纸,500.0,150.0,150.0,NaN,NaN,2.0,2.0,148.0
1,材料纸,FB503,方格材料纸,500.0,98.0,98.0,NaN,NaN,NaN,NaN,98.0
2,材料纸,J1601,简装双行材料纸,270.0,81.0,81.0,NaN,NaN,NaN,NaN,81.0
3,材料纸,J1602,简装单行材料纸,270.0,115.0,115.0,NaN,NaN,NaN,NaN,115.0
4,材料纸,J1603,简装方格材料纸,270.0,54.0,54.0,NaN,NaN,NaN,NaN,54.0
...,...,...,...,...,...,...,...,...,...,...,...
588,卡通硬抄,N0663,D32K96P卡通硬面抄,108.0,102.0,102.0,NaN,NaN,NaN,NaN,102.0
589,卡通硬抄,N0664,D32K128P卡通硬面抄,84.0,48.0,48.0,NaN,NaN,NaN,NaN,48.0
590,卡通硬抄,N0667,36K64P卡通硬面抄,140.0,4.0,4.0,NaN,NaN,NaN,NaN,4.0
591,卡通硬抄,N0668,36K64P卡通硬面学生日记,140.0,70.0,70.0,NaN,NaN,NaN,NaN,70.0
592,卡通硬抄,N0669,D32K64P硬面学生日记,144.0,72.0,72.0,NaN,NaN,NaN,NaN,72.0

In [81]:
gp = df_caoben1.groupby('class05')
d = gp.get_group('长沙版小学生本')
d

,class05,code,stock,content,begin_jian,yesterday_jian,yesterday_ruku,ruku_jian,yesterday_chuku,chuku_jian,end_jian
264,长沙版小学生本,CS101,32K生字本,1200.000000,67.00,67.00,NaN,NaN,NaN,NaN,67.00
265,长沙版小学生本,CS102,32K田字本,1199.438202,7.12,7.12,NaN,NaN,NaN,NaN,7.12
266,长沙版小学生本,CS105,32K拼音本,1200.000000,64.00,64.00,NaN,NaN,NaN,NaN,64.00
267,长沙版小学生本,CS107,32K作文本,1200.000000,136.00,136.00,NaN,NaN,NaN,NaN,136.00
268,长沙版小学生本,CS108,32K数学本,1200.000000,142.00,142.00,NaN,NaN,1.0,1.0,141.00
269,长沙版小学生本,CS110,32K语文练习本,1200.000000,12.00,12.00,NaN,NaN,NaN,NaN,12.00

In [90]:
dict(zip(d.columns,d.sum()))

# d1 = pd.concat([d,d.sum()],axis = 0)
# d1

{'class05': '长沙版小学生本长沙版小学生本长沙版小学生本长沙版小学生本长沙版小学生本长沙版小学生本',
 'code': 'CS101CS102CS105CS107CS108CS110',
 'stock': '32K生字本32K田字本32K拼音本32K作文本32K数学本32K语文练习本',
 'content': 7199.438202247191,
 'begin_jian': 428.12,
 'yesterday_jian': 428.12,
 'yesterday_ruku': 0.0,
 'ruku_jian': 0.0,
 'yesterday_chuku': 1.0,
 'chuku_jian': 1.0,
 'end_jian': 427.12}

In [91]:
d

,class05,code,stock,content,begin_jian,yesterday_jian,yesterday_ruku,ruku_jian,yesterday_chuku,chuku_jian,end_jian
264,长沙版小学生本,CS101,32K生字本,1200.000000,67.00,67.00,NaN,NaN,NaN,NaN,67.00
265,长沙版小学生本,CS102,32K田字本,1199.438202,7.12,7.12,NaN,NaN,NaN,NaN,7.12
266,长沙版小学生本,CS105,32K拼音本,1200.000000,64.00,64.00,NaN,NaN,NaN,NaN,64.00
267,长沙版小学生本,CS107,32K作文本,1200.000000,136.00,136.00,NaN,NaN,NaN,NaN,136.00
268,长沙版小学生本,CS108,32K数学本,1200.000000,142.00,142.00,NaN,NaN,1.0,1.0,141.00
269,长沙版小学生本,CS110,32K语文练习本,1200.000000,12.00,12.00,NaN,NaN,NaN,NaN,12.00

In [131]:
d1 = d.copy()
d1 = d1.set_index(['class05','code','stock','content'])
d1

                                    begin_jian  yesterday_jian  \
class05 code  stock    content
长沙版小学生本 CS101 32K生字本   1200.000000       67.00           67.00
        CS102 32K田字本   1199.438202        7.12            7.12
        CS105 32K拼音本   1200.000000       64.00           64.00
        CS107 32K作文本   1200.000000      136.00          136.00
        CS108 32K数学本   1200.000000      142.00          142.00
        CS110 32K语文练习本 1200.000000       12.00           12.00

                                    yesterday_ruku  ruku_jian  \
class05 code  stock    content
长沙版小学生本 CS101 32K生字本   1200.000000             NaN        NaN
        CS102 32K田字本   1199.438202             NaN        NaN
        CS105 32K拼音本   1200.000000             NaN        NaN
        CS107 32K作文本   1200.000000             NaN        NaN
        CS108 32K数学本   1200.000000             NaN        NaN
        CS110 32K语文练习本 1200.000000             NaN        NaN

                                    yesterday_chuku  chuku_jian  end_jian
class05 code  stock    content
长沙版小学生本 CS101 32K生字本   1200.000000              NaN         NaN     67.00
        CS102 32K田字本   1199.438202              NaN         NaN      7.12
        CS105 32K拼音本   1200.000000              NaN         NaN     64.00
        CS107 32K作文本   1200.000000              NaN         NaN    136.00
        CS108 32K数学本   1200.000000              1.0         1.0    141.00
        CS110 32K语文练习本 1200.000000              NaN         NaN     12.00

In [93]:
d1.sum()

begin_jian         428.12
yesterday_jian     428.12
yesterday_ruku       0.00
ruku_jian            0.00
yesterday_chuku      1.00
chuku_jian           1.00
end_jian           427.12
dtype: float64

In [124]:
dic = dict(zip(d1.columns,d1.sum()))
dic

{'begin_jian': 428.12,
 'yesterday_jian': 428.12,
 'yesterday_ruku': 0.0,
 'ruku_jian': 0.0,
 'yesterday_chuku': 1.0,
 'chuku_jian': 1.0,
 'end_jian': 427.12}

In [126]:
d1.loc[len(d1)] = dic

In [128]:
d1.to_excel('111-2.xlsx')

C:\Users\redda\AppData\Local\Temp\ipykernel_32444\1558479852.py:1: UserWarning: Pandas requires version '3.0.5' or newer of 'xlsxwriter' (version '3.0.3' currently installed).
  d1.to_excel('111-2.xlsx')

In [99]:
d3 = pd.DataFrame(dic,index = ['class05','code','stock','content'])
d3

,begin_jian,yesterday_jian,yesterday_ruku,ruku_jian,yesterday_chuku,chuku_jian,end_jian
class05,428.12,428.12,0.0,0.0,1.0,1.0,427.12
code,428.12,428.12,0.0,0.0,1.0,1.0,427.12
stock,428.12,428.12,0.0,0.0,1.0,1.0,427.12
content,428.12,428.12,0.0,0.0,1.0,1.0,427.12

In [122]:
d.sum()

class05            长沙版小学生本长沙版小学生本长沙版小学生本长沙版小学生本长沙版小学生本长沙版小学生本
code                           CS101CS102CS105CS107CS108CS110
stock                  32K生字本32K田字本32K拼音本32K作文本32K数学本32K语文练习本
content                                           7199.438202
begin_jian                                             428.12
yesterday_jian                                         428.12
yesterday_ruku                                            0.0
ruku_jian                                                 0.0
yesterday_chuku                                           1.0
chuku_jian                                                1.0
end_jian                                               427.12
dtype: object

In [130]:
d1 = d1.reset_index()
d1.to_excel('111-3.xlsx',index = False)

C:\Users\redda\AppData\Local\Temp\ipykernel_32444\2026181759.py:2: UserWarning: Pandas requires version '3.0.5' or newer of 'xlsxwriter' (version '3.0.3' currently installed).
  d1.to_excel('111-3.xlsx',index = False)

In [132]:
d2 = d1.reset_index()
d2

,class05,code,stock,content,begin_jian,yesterday_jian,yesterday_ruku,ruku_jian,yesterday_chuku,chuku_jian,end_jian
0,长沙版小学生本,CS101,32K生字本,1200.000000,67.00,67.00,NaN,NaN,NaN,NaN,67.00
1,长沙版小学生本,CS102,32K田字本,1199.438202,7.12,7.12,NaN,NaN,NaN,NaN,7.12
2,长沙版小学生本,CS105,32K拼音本,1200.000000,64.00,64.00,NaN,NaN,NaN,NaN,64.00
3,长沙版小学生本,CS107,32K作文本,1200.000000,136.00,136.00,NaN,NaN,NaN,NaN,136.00
4,长沙版小学生本,CS108,32K数学本,1200.000000,142.00,142.00,NaN,NaN,1.0,1.0,141.00
5,长沙版小学生本,CS110,32K语文练习本,1200.000000,12.00,12.00,NaN,NaN,NaN,NaN,12.00

In [133]:
d2.sum()

class05            长沙版小学生本长沙版小学生本长沙版小学生本长沙版小学生本长沙版小学生本长沙版小学生本
code                           CS101CS102CS105CS107CS108CS110
stock                  32K生字本32K田字本32K拼音本32K作文本32K数学本32K语文练习本
content                                           7199.438202
begin_jian                                             428.12
yesterday_jian                                         428.12
yesterday_ruku                                            0.0
ruku_jian                                                 0.0
yesterday_chuku                                           1.0
chuku_jian                                                1.0
end_jian                                               427.12
dtype: object

In [134]:
d2.loc['长沙版小学生本小计'] = d2.sum()

In [135]:
d2

,class05,code,stock,content,begin_jian,yesterday_jian,yesterday_ruku,ruku_jian,yesterday_chuku,chuku_jian,end_jian
0,长沙版小学生本,CS101,32K生字本,1200.000000,67.00,67.00,NaN,NaN,NaN,NaN,67.00
1,长沙版小学生本,CS102,32K田字本,1199.438202,7.12,7.12,NaN,NaN,NaN,NaN,7.12
2,长沙版小学生本,CS105,32K拼音本,1200.000000,64.00,64.00,NaN,NaN,NaN,NaN,64.00
3,长沙版小学生本,CS107,32K作文本,1200.000000,136.00,136.00,NaN,NaN,NaN,NaN,136.00
4,长沙版小学生本,CS108,32K数学本,1200.000000,142.00,142.00,NaN,NaN,1.0,1.0,141.00
5,长沙版小学生本,CS110,32K语文练习本,1200.000000,12.00,12.00,NaN,NaN,NaN,NaN,12.00
长沙版小学生本小计,长沙版小学生本长沙版小学生本长沙版小学生本长沙版小学生本长沙版小学生本长沙版小学生本,CS101CS102CS105CS107CS108CS110,32K生字本32K田字本32K拼音本32K作文本32K数学本32K语文练习本,7199.438202,428.12,428.12,0.0,0.0,1.0,1.0,427.12

In [138]:
xiaoji = d2.iloc[-1,:4]

In [139]:
d2.iloc[-1,:4] = ['长沙版小学生本小计','','','']
d2

C:\Users\redda\AppData\Local\Temp\ipykernel_32444\3412410049.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  d2.iloc[-1,:4] = ['长沙版小学生本小计','','','']

,class05,code,stock,content,begin_jian,yesterday_jian,yesterday_ruku,ruku_jian,yesterday_chuku,chuku_jian,end_jian
0,长沙版小学生本,CS101,32K生字本,1200.0,67.00,67.00,NaN,NaN,NaN,NaN,67.00
1,长沙版小学生本,CS102,32K田字本,1199.438202,7.12,7.12,NaN,NaN,NaN,NaN,7.12
2,长沙版小学生本,CS105,32K拼音本,1200.0,64.00,64.00,NaN,NaN,NaN,NaN,64.00
3,长沙版小学生本,CS107,32K作文本,1200.0,136.00,136.00,NaN,NaN,NaN,NaN,136.00
4,长沙版小学生本,CS108,32K数学本,1200.0,142.00,142.00,NaN,NaN,1.0,1.0,141.00
5,长沙版小学生本,CS110,32K语文练习本,1200.0,12.00,12.00,NaN,NaN,NaN,NaN,12.00
长沙版小学生本小计,长沙版小学生本小计,,,,428.12,428.12,0.0,0.0,1.0,1.0,427.12