In [3]:
import pandas as pd
import re

# file = 'pandas正则分列示例.xlsx'
# df = pd.read_excel(file)
df = pd.read_clipboard()
df
# df2 = df['车型名称'].map(lambda x: re.sub('[A-Z0-9. ]+', ',', x)).str.split(',', expand=True)
# df = pd.concat([df, df2], axis=1)
# df.columns = ['车型名称', '品牌', '车型']
# print(df)

ParserError: Expected 5 fields in line 15, saw 6. Error could possibly be due to quotes being ignored when a multi-char delimiter is used.

In [4]:
df2 = df['车型名称'].map(lambda x: re.sub('[A-Z0-9. ]+', ',', x)).str.split(',', expand=True)
df2

       0       1
0   东风标致      轿车
1     大众      轿车
2     大众      轿车
3     大众      轿车
4     大众      轿车
5     大众      轿车
6     大众      轿车
7     大众      轿车
8     大众      轿车
9     大众      轿车
10    大众      轿车
11    大众      轿车
12    颐达      轿车
13    精灵      轿车
14  雷克萨斯     越野车
15   自由客     越野车
16    思域      轿车
17  雷克萨斯     越野车
18    丰田  混合动力轿车
19    别克      轿车
20    炫威      轿车
21    东风  多用途乘用车
22    本田      轿车