In [1]:
import pandas as pd
from openpyxl import load_workbook
from openpyxl.styles import Font,PatternFill, colors
# 加载 Excel 文件
workbook = load_workbook('team.xlsx')
# 选择工作表
sheet = workbook.active
# 选取单元格范围
df = pd.DataFrame(sheet['B5':'E10'])
df

,0,1,2,3
0,<Cell 'Sheet1'.B5>,<Cell 'Sheet1'.C5>,<Cell 'Sheet1'.D5>,<Cell 'Sheet1'.E5>
1,<Cell 'Sheet1'.B6>,<Cell 'Sheet1'.C6>,<Cell 'Sheet1'.D6>,<Cell 'Sheet1'.E6>
2,<Cell 'Sheet1'.B7>,<Cell 'Sheet1'.C7>,<Cell 'Sheet1'.D7>,<Cell 'Sheet1'.E7>
3,<Cell 'Sheet1'.B8>,<Cell 'Sheet1'.C8>,<Cell 'Sheet1'.D8>,<Cell 'Sheet1'.E8>
4,<Cell 'Sheet1'.B9>,<Cell 'Sheet1'.C9>,<Cell 'Sheet1'.D9>,<Cell 'Sheet1'.E9>
5,<Cell 'Sheet1'.B10>,<Cell 'Sheet1'.C10>,<Cell 'Sheet1'.D10>,<Cell 'Sheet1'.E10>

In [2]:
def modify_style(cell):# 设置样式
    bold_font =Font(size=14,bold=True, color='FF0000')
    yellow_fill = PatternFill(start_color='00FF00',
                              end_color='00FF00',
                             fill_type='solid')
    # 修改样式
    cell.font = bold_font
    cell.fill = yellow_fill

In [3]:
df.map(modify_style)

      0     1     2     3
0  None  None  None  None
1  None  None  None  None
2  None  None  None  None
3  None  None  None  None
4  None  None  None  None
5  None  None  None  None

In [4]:
# 保存修改后的 Excel 文件
workbook.save('team_formatted.xlsx')
# 关闭 Excel 文件
workbook.close()