In [1]:
'''

'''
import pandas as pd
score_data=pd.DataFrame({"student":["01","01","01","01","01","01","01","02","02","02","02","02","02","02"],
                   "teacher":["A","B","A","B","C","A","A","A","A","A","B","B","C","C"],
                   "course":["031","031","041","041","051","051","051","031","031","031","051","051","061","061"],
                   "homework":[100,100,98,97,100,99,98,98,92,90,92,96,97,100],
                   "final_score":[90,95,88,81,86,92,95,77,61,65,59,69,80,82]})

dfs1 = score_data.groupby(['student','teacher','course']).sum()

dfs2 =dfs1.copy()  ##复制新表，以免动原始表，影响多次合计

###获取小计的index列表
index1 = [ x[:2] for x in dfs1.index]  #只截取前两个index进行小计（因为第三个index已经是最明细了无需再合计）
list1 = list(set(index1))      ### 消除重复项
list1.sort(key = index1.index)  ###按照原index排序
list1 ### [('01', 'A'), ('01', 'B'), ('01', 'C'), ('02', 'A'), ('02', 'B'), ('02', 'C')]

###获取合计的index列表(与上面一样）
index2 = [ x[:1] for x in dfs1.index]
list2 = list(set(index2))
list2.sort(key = index2.index)
list2 ### [('01', 'A'), ('01', 'B'), ('01', 'C'), ('02', 'A'), ('02', 'B'), ('02', 'C')]


###对dfs2添加小计
for i in list1:
    y = dfs1.loc[i]  ## 筛选对应的DF
    i1, i2 = i
    dfs2.loc[(i1,i2,'小计')]=y.sum()
    dfs2= dfs2.sort_index() 
    
### 添加合计
for i in list2:
    y = dfs1.loc[i]  ## 筛选对应的DF
    i1 = i[0]
    dfs2.loc[(i1,'合计','')]=y.sum()
    dfs2= dfs2.sort_index() 
    list_temp = []

###添加总计
dfs2.loc[('总计','','')]=list(dfs1.sum())
dfs2

                        homework  final_score
student teacher course
01      A       031          100           90
                041           98           88
                051          197          187
                小计           395          365
        B       031          100           95
                041           97           81
                小计           197          176
        C       051          100           86
                小计           100           86
        合计                   692          627
02      A       031          280          203
                小计           280          203
        B       051          188          128
                小计           188          128
        C       061          197          162
                小计           197          162
        合计                   665          493
总计                          1357         1120

In [ ]:
''' 形成函数
以下为函数形式，只要是3列index的均可以直接用此函数。
'''
def df_add_sum_row(dfs1):
    dfs2 =dfs1.copy()  ##复制新表，以免动原始表，影响多次合计

    ###获取小计的index列表
    index1 = [ x[:2] for x in dfs1.index]  #只截取前两个index进行小计（因为第三个index已经是最明细了无需再合计）
    list1 = list(set(index1))      ### 消除重复项
    list1.sort(key = index1.index)  ###按照原index排序
    list1 ### [('01', 'A'), ('01', 'B'), ('01', 'C'), ('02', 'A'), ('02', 'B'), ('02', 'C')]

    ###获取合计的index列表(与上面一样）
    index2 = [ x[:1] for x in dfs1.index]
    list2 = list(set(index2))
    list2.sort(key = index2.index)
    list2 ### [('01', 'A'), ('01', 'B'), ('01', 'C'), ('02', 'A'), ('02', 'B'), ('02', 'C')]


    ###对dfs2添加小计
    for i in list1:
        y = dfs1.loc[i]  ## 筛选对应的DF
        i1, i2 = i
        dfs2.loc[(i1,i2,'小计')]=y.sum()
        dfs2= dfs2.sort_index() 

    ### 添加合计
    for i in list2:
        y = dfs1.loc[i]  ## 筛选对应的DF
        i1 = i[0]
        dfs2.loc[(i1,'合计','')]=y.sum()
        dfs2= dfs2.sort_index() 
        list_temp = []

    ###添加总计
    dfs2.loc[('总计','','')]=list(dfs1.sum())
    return dfs2