In [1]:
import pandas as pd
import os
import easygui

In [3]:
df0 = pd.read_clipboard()
df0

,商户订单号,发生时间,收入金额（+元）,支出金额（-元）,账务类型,备注,业务描述
0,240508-045398148751866,2024/5/19 10:30,4.8,0.00,交易收入,-,0010002|交易收入-订单收入
1,240508-045398148751866,2024/5/19 10:30,0.0,-0.03,技术服务费,-,0030002|技术服务费-基础技术服务费
2,240508-045618327280511,2024/5/19 10:30,0.0,-0.04,技术服务费,-,0030002|技术服务费-基础技术服务费
3,240508-045618327280511,2024/5/19 10:30,6.3,0.00,交易收入,-,0010002|交易收入-订单收入
4,240508-070988623551931,2024/5/19 10:30,0.0,-0.06,技术服务费,-,0030002|技术服务费-基础技术服务费
...,...,...,...,...,...,...,...
912,240531-629470728633548,2024/5/31 11:58,0.0,-0.04,技术服务费,先用后付技术服务费,0030005|技术服务费-先用后付技术服务费
913,240531-637156728500276,2024/5/31 13:27,0.0,-0.15,其他服务,消费者体验提升计划费用，扣费编号：B240531132730925-7729-0100306881,0050002|服务支出-消费者体验提升计划
914,240531-662951749973440,2024/5/31 13:27,0.0,-0.15,其他服务,消费者体验提升计划费用，扣费编号：B240531132730925-7729-0100306881,0050002|服务支出-消费者体验提升计划
915,240531-670255091903555,2024/5/31 13:27,0.0,-0.15,其他服务,消费者体验提升计划费用，扣费编号：B240531132730925-7729-0100306881,0050002|服务支出-消费者体验提升计划
916,240531-673421770910008,2024/5/31 13:57,0.0,-0.15,其他服务,消费者体验提升计划费用，扣费编号：B240531135752612-0846-0100306881,0050002|服务支出-消费者体验提升计划

In [7]:
df1 = pd.read_clipboard()
df1

ParserError: Expected 28 fields in line 39, saw 29. Error could possibly be due to quotes being ignored when a multi-char delimiter is used.

In [8]:
df1 = pd.read_excel(r"F:\a00nutstore\008\zw08\2024\202405\电商\2024.5.1-5.31销售数据正.xlsx")
df1

,商品,订单号,订单状态,商品数量(件),支付时间,发货时间,确认收货时间,商品id,商品规格,样式ID,...,商品三级类目,商家编码-规格维度,商家编码-商品维度,订单成交时间,商品总价(元),店铺优惠折扣(元),平台优惠折扣(元),多多支付立减金额(元),用户实付金额(元),商家实收金额(元)
0,莱特5本36页牛皮学生作业本16K学校统一语文练习本小学汉语拼音本,240531-137636093490053,已收货,1,2024-05-31 23:36:50,2024-06-01 12:24:57,2024-06-03 15:31:54,609881478958,16K练习本(5本),1599890404782,...,课业本教学用本,N0785,\t,2024-05-31 23:36:50,4.50,0.0,0.00,0.01,4.50,4.50
1,莱特5本加厚200页B5学生笔记本办公记事本白领工作记录本子笔记本,240531-619655995050764,已收货,1,2024-05-31 23:34:56,2024-06-01 12:24:57,2024-06-03 17:31:32,608059073339,B5五本（每本100张）,1593732323449,...,笔记本记事本,N0584,\t,2024-05-31 23:34:57,15.00,0.0,0.00,0.00,15.00,15.00
2,莱特5本36页牛皮学生作业本16K学校统一语文练习本小学汉语拼音本,240531-084158738200605,已收货,2,2024-05-31 23:11:34,2024-06-01 12:24:57,2024-06-04 12:35:40,609881478958,16K生字本(5本),1599890404781,...,课业本教学用本,N0780,\t,2024-05-31 23:11:34,9.00,0.9,5.00,0.00,3.10,8.10
3,莱特5本36页牛皮学生作业本16K学校统一语文练习本小学汉语拼音本,240531-615304415021401,已发货，待收货,4,2024-05-31 22:57:49,2024-06-01 12:24:57,\t,609881478958,16K作文本300格(5本),1599890404771,...,课业本教学用本,N0784(300格),\t,2024-05-31 22:57:49,18.00,1.8,3.24,0.00,12.96,16.20
4,莱特5本36页牛皮学生作业本16K学校统一语文练习本小学汉语拼音本,240531-443505723181401,已发货，待收货,4,2024-05-31 22:57:49,2024-06-01 12:24:57,\t,609881478958,16K方格语文本(5本),1599890404773,...,课业本教学用本,N0781(方格),\t,2024-05-31 22:57:49,18.00,1.8,3.24,0.00,12.96,16.20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
388,莱特10本装草稿纸作业草稿本演算学生空白大学生考研验算加厚纸张,240508-045398148751866,已收货,1,2024-05-08 22:18:26,2024-05-09 10:24:39,2024-05-19 10:24:39,612572388478,3本装/每本40张（共120张）,1596114591038,...,文稿纸草稿纸,\t,\t,2024-05-08 22:18:27,4.80,0.0,0.00,0.00,4.80,4.80
389,莱特10本装草稿纸作业草稿本演算学生空白大学生考研验算加厚纸张,240508-621218383594022,已收货,1,2024-05-08 22:14:06,2024-05-09 10:24:39,2024-05-19 10:24:39,612572388478,10本装/每本40张（400张）,1596114591035,...,文稿纸草稿纸,\t,\t,2024-05-08 22:14:07,10.50,0.0,0.00,0.00,10.50,10.50
390,莱特10本装草稿纸作业草稿本演算学生空白大学生考研验算加厚纸张,240508-553878854563408,已收货,1,2024-05-08 20:28:52,2024-05-09 10:24:39,2024-05-19 10:24:39,612572388478,5本装/每本40张（共200张）,1596114591034,...,文稿纸草稿纸,\t,\t,2024-05-08 20:28:52,6.30,0.0,0.00,0.00,6.30,6.30
391,5本装莱特180°平摊B5学生笔记本办公记事本加厚纸张工作记录本子,240508-185692363713721,已收货,1,2024-05-08 20:00:17,2024-05-09 10:24:39,2024-05-19 10:24:39,608059073339,A5五本（每本40张）,1593732323450,...,笔记本记事本,DWXB5,\t,2024-05-08 20:00:17,10.89,1.0,6.00,0.00,3.89,9.89
392,莱特10本装草稿纸作业草稿本演算学生空白大学生考研验算加厚纸张,240508-045618327280511,已收货,1,2024-05-08 19:39:35,2024-05-09 10:24:14,2024-05-19 10:24:14,612572388478,5本装/每本40张（共200张）,1596114591034,...,文稿纸草稿纸,\t,\t,2024-05-08 19:39:36,6.30,0.0,0.00,0.00,6.30,6.30

In [9]:
gp0 = df0.groupby('商户订单号')
gp0

In [10]:
gp0['收入金额（+元）'].sum()

商户订单号
240508-045398148751866     4.80
240508-045618327280511     6.30
240508-070988623551931    10.50
240508-185692363713721     9.89
240508-188271860572818    10.50
                          ...
240531-629470728633548     4.05
240531-637156728500276     0.00
240531-662951749973440     0.00
240531-670255091903555     0.00
240531-673421770910008     0.00
Name: 收入金额（+元）, Length: 439, dtype: float64

In [12]:
gp0['支出金额（-元）'].sum()

商户订单号
240508-045398148751866   -0.03
240508-045618327280511   -0.04
240508-070988623551931   -0.06
240508-185692363713721   -0.06
240508-188271860572818   -0.06
                          ...
240531-629470728633548   -4.09
240531-637156728500276   -0.15
240531-662951749973440   -0.15
240531-670255091903555   -0.15
240531-673421770910008   -0.15
Name: 支出金额（-元）, Length: 439, dtype: float64

In [15]:
df11 = pd.concat([gp0['收入金额（+元）'].sum(),gp0['支出金额（-元）'].sum()],axis =1)
df11

                        收入金额（+元）  支出金额（-元）
商户订单号
240508-045398148751866      4.80     -0.03
240508-045618327280511      6.30     -0.04
240508-070988623551931     10.50     -0.06
240508-185692363713721      9.89     -0.06
240508-188271860572818     10.50     -0.06
...                          ...       ...
240531-629470728633548      4.05     -4.09
240531-637156728500276      0.00     -0.15
240531-662951749973440      0.00     -0.15
240531-670255091903555      0.00     -0.15
240531-673421770910008      0.00     -0.15

[439 rows x 2 columns]

In [16]:
gp1 = df1.groupby('订单号')
gp1

In [18]:
df22 = gp1['商品总价(元)'].sum()
df22

订单号
240508-045398148751866     4.80
240508-045618327280511     6.30
240508-070988623551931    10.50
240508-185692363713721    10.89
240508-188271860572818    10.50
                          ...
240531-642834777751297     9.00
240531-649571868180332     4.50
240531-662951749973440     9.00
240531-670255091903555     4.50
240531-673421770910008     9.00
Name: 商品总价(元), Length: 393, dtype: float64

In [21]:
df22.columns = ['商户订单号','金额']
df22 = pd.DataFrame(df22)
df22

                        商品总价(元)
订单号
240508-045398148751866     4.80
240508-045618327280511     6.30
240508-070988623551931    10.50
240508-185692363713721    10.89
240508-188271860572818    10.50
...                         ...
240531-642834777751297     9.00
240531-649571868180332     4.50
240531-662951749973440     9.00
240531-670255091903555     4.50
240531-673421770910008     9.00

[393 rows x 1 columns]

In [22]:
df = df11.merge(df22,how = 'outer',left_index = '商户订单号',right_index = '订单号')
df

ValueError: left_index parameter must be of type bool, not <class 'str'>

In [23]:
夺1

NameError: name '夺1' is not defined

In [24]:
df11

                        收入金额（+元）  支出金额（-元）
商户订单号
240508-045398148751866      4.80     -0.03
240508-045618327280511      6.30     -0.04
240508-070988623551931     10.50     -0.06
240508-185692363713721      9.89     -0.06
240508-188271860572818     10.50     -0.06
...                          ...       ...
240531-629470728633548      4.05     -4.09
240531-637156728500276      0.00     -0.15
240531-662951749973440      0.00     -0.15
240531-670255091903555      0.00     -0.15
240531-673421770910008      0.00     -0.15

[439 rows x 2 columns]

In [25]:
df22

                        商品总价(元)
订单号
240508-045398148751866     4.80
240508-045618327280511     6.30
240508-070988623551931    10.50
240508-185692363713721    10.89
240508-188271860572818    10.50
...                         ...
240531-642834777751297     9.00
240531-649571868180332     4.50
240531-662951749973440     9.00
240531-670255091903555     4.50
240531-673421770910008     9.00

[393 rows x 1 columns]

In [26]:
df = df11.merge(df22,how = 'outer',left_index = '商户订单号',right_index = '订单号')
df2

ValueError: left_index parameter must be of type bool, not <class 'str'>

In [27]:
df11.index_name = '订单号'
df11

                        收入金额（+元）  支出金额（-元）
商户订单号
240508-045398148751866      4.80     -0.03
240508-045618327280511      6.30     -0.04
240508-070988623551931     10.50     -0.06
240508-185692363713721      9.89     -0.06
240508-188271860572818     10.50     -0.06
...                          ...       ...
240531-629470728633548      4.05     -4.09
240531-637156728500276      0.00     -0.15
240531-662951749973440      0.00     -0.15
240531-670255091903555      0.00     -0.15
240531-673421770910008      0.00     -0.15

[439 rows x 2 columns]