In [1]:
import pandas as pd
import numpy as np
from io import StringIO

In [2]:
data = '''
对话开始 >>
李庆辉 2020-05-15 12:33:50
    你好，可以退货吗
客服999 2020-05-15 12:33:55 >>
    工号999很高兴为您服务~。
客服999 2020-05-15 12:33:53
    您好
客服999 2020-05-15 12:34:04
    您可以自己操作申请取消订单的。
李庆辉 2020-05-15 12:34:04
    退款多久到账呢？
客服999 2020-05-15 12:34:28
    一般1-7个工作日
李庆辉 2020-05-15 12:35:01
    OMG! 好久呢
李庆辉 2020-05-15 12:40:55
    能不能快点
客服999 2020-05-15 12:42:23
    一般情况下很快就会到账的。
李庆辉 2020-05-15 12:43:04
    OMG! 好久呢
客服999 2020-05-15 12:44:01
    一般情况下很快就会到账的。
对话结束  >>
    长时间未回复，对话结束
'''

In [3]:
df = pd.read_csv(StringIO(data), names=['chats'], dtype='string')
df

                           chats
0                        对话开始 >>
1        李庆辉 2020-05-15 12:33:50
2                       你好，可以退货吗
3   客服999 2020-05-15 12:33:55 >>
4                 工号999很高兴为您服务~。
5      客服999 2020-05-15 12:33:53
6                             您好
7      客服999 2020-05-15 12:34:04
8                您可以自己操作申请取消订单的。
9        李庆辉 2020-05-15 12:34:04
10                      退款多久到账呢？
11     客服999 2020-05-15 12:34:28
12                     一般1-7个工作日
13       李庆辉 2020-05-15 12:35:01
14                      OMG! 好久呢
15       李庆辉 2020-05-15 12:40:55
16                         能不能快点
17     客服999 2020-05-15 12:42:23
18                 一般情况下很快就会到账的。
19       李庆辉 2020-05-15 12:43:04
20                      OMG! 好久呢
21     客服999 2020-05-15 12:44:01
22                 一般情况下很快就会到账的。
23                      对话结束  >>
24                   长时间未回复，对话结束

In [11]:
df1 = (
    df.loc[~(df.chats.str.endswith('>>')) & ~(df.chats.str.contains('\t'))]
    # 排除系统自动提示内容
    .assign(name=lambda x: x.chats.str.split().str[0]) # 提取双方昵称
    # 判断是否客服（客服昵称中有“客服”字样）
    .assign(staff=lambda x: x.name.str.contains('客服'))
   
)
df1

                        chats             name  staff
1     李庆辉 2020-05-15 12:33:50              李庆辉  False
2                    你好，可以退货吗         你好，可以退货吗  False
4              工号999很高兴为您服务~。   工号999很高兴为您服务~。  False
5   客服999 2020-05-15 12:33:53            客服999   True
6                          您好               您好  False
7   客服999 2020-05-15 12:34:04            客服999   True
8             您可以自己操作申请取消订单的。  您可以自己操作申请取消订单的。  False
9     李庆辉 2020-05-15 12:34:04              李庆辉  False
10                   退款多久到账呢？         退款多久到账呢？  False
11  客服999 2020-05-15 12:34:28            客服999   True
12                  一般1-7个工作日        一般1-7个工作日  False
13    李庆辉 2020-05-15 12:35:01              李庆辉  False
14                   OMG! 好久呢             OMG!  False
15    李庆辉 2020-05-15 12:40:55              李庆辉  False
16                      能不能快点            能不能快点  False
17  客服999 2020-05-15 12:42:23            客服999   True
18              一般情况下很快就会到账的。    一般情况下很快就会到账的。  False
19    李庆辉 2020-05-15 12:43:04              李庆辉  False
20                   OMG! 好久呢             OMG!  False
21  客服999 2020-05-15 12:44:01            客服999   True
22              一般情况下很快就会到账的。    一般情况下很快就会到账的。  False
24                长时间未回复，对话结束      长时间未回复，对话结束  False

In [13]:
df2 = df1[df1.staff == True]
df2
# .assign(time=lambda x: pd.to_datetime(x.chats.str[-20:])) # 提取并转换为时间类型
#     .sort_values('time') # 按时间先后排期

                        chats   name  staff
5   客服999 2020-05-15 12:33:53  客服999   True
7   客服999 2020-05-15 12:34:04  客服999   True
11  客服999 2020-05-15 12:34:28  客服999   True
17  客服999 2020-05-15 12:42:23  客服999   True
21  客服999 2020-05-15 12:44:01  客服999   True

In [15]:
df2 = df2.assign(time=lambda x: pd.to_datetime(x.chats.str[-20:])) # 提取并转换为时间类型
df2

                        chats   name  staff                time
5   客服999 2020-05-15 12:33:53  客服999   True 2020-05-15 12:33:53
7   客服999 2020-05-15 12:34:04  客服999   True 2020-05-15 12:34:04
11  客服999 2020-05-15 12:34:28  客服999   True 2020-05-15 12:34:28
17  客服999 2020-05-15 12:42:23  客服999   True 2020-05-15 12:42:23
21  客服999 2020-05-15 12:44:01  客服999   True 2020-05-15 12:44:01

In [16]:
df2.sort_values('time') # 按时间先后排期

                        chats   name  staff                time
5   客服999 2020-05-15 12:33:53  客服999   True 2020-05-15 12:33:53
7   客服999 2020-05-15 12:34:04  客服999   True 2020-05-15 12:34:04
11  客服999 2020-05-15 12:34:28  客服999   True 2020-05-15 12:34:28
17  客服999 2020-05-15 12:42:23  客服999   True 2020-05-15 12:42:23
21  客服999 2020-05-15 12:44:01  客服999   True 2020-05-15 12:44:01

In [20]:
(
    df.loc[~(df.chats.str.endswith('>>')) & ~(df.chats.str.contains('\t'))] # 排除系统内容
    .assign(name=lambda x: x.chats.str.split().str[0]) # 提取双方昵称
    # 判断是否客服（客服昵称中有“客服”字样）
    .assign(staff=lambda x: x.name.str.contains('客服'))
    .assign(time=lambda x: pd.to_datetime(x.chats.str[-20:])) # 提取并转换为时间类型
    .sort_values('time') # 按时间先后排期
    # 开始求平均时长，保留一方连续发言情况中的第一条
    .loc[lambda x: (x[['name']].shift() != x[['name']]).any(axis=1)]
    .assign(diff=lambda x: x.time.diff()) # 求先后对话的时间差
    .assign(avg=lambda x: x['diff'].mean().seconds) # 对所有的时间差求平均数，单位为秒
)

SyntaxError: invalid syntax (637361497.py, line 6)