In [ ]:
import pandas as pd
import numpy as np
import re
import os

In [ ]:
fname = r"F:\repos\fish\新芭案例\工资\双佳工资表.xls"
sheet_name = r'2024.2'
df = pd.read_excel(fname,sheet_name = sheet_name,skiprows = 3)
df = df.loc[~df['姓名'].isnull()]
df = df.drop(['序号'],axis = 1)
for i in ['公司','部门'][::-1]:
    df.insert(0,i,'')
df['公司'] = '双佳'
df['账      号'] = df['账      号'].fillna('现金')
df['部门'] = df['账      号']
df = df[df['账      号'].str.contains('账      号|合计|本页') == False] 
lst = [np.nan if '计' not in i else i for i in df['账      号']]
df = df.assign(部门=lst)
df['部门'].fillna(method="bfill",axis=0, inplace=True)
df = df[df['账      号'].str.contains('计') == False] 
pattern = r'(?P<bumen>\w+)小计(?:.*)'
regexp = re.compile(pattern)
repl = lambda m : m.group('bumen')
df['部门'] = df['部门'].str.replace(regexp,repl,regex = True)
index = df.columns.to_list().index('考勤')
for i in ['绩效','安全分','安全责任基数'	,'安全奖'][::-1]:
    df.insert(index,i,0)
df.to_excel('sj.xlsx')

In [ ]:
fname = r"F:\repos\fish\新芭案例\工资\莱特工资表.xls"
sheet_name = r'2024.2'
df = pd.read_excel(fname,sheet_name = sheet_name,skiprows = 3)
df = df.loc[~df['姓名'].isnull()]
df = df.drop(['序号'],axis = 1)
for i in ['公司','部门'][::-1]:
    df.insert(0,i,'')
df['公司'] = '双佳'
df['账      号'] = df['账      号'].fillna('现金')
df['部门'] = df['账      号']
df = df[df['账      号'].str.contains('账      号|合计|本页') == False] 
lst = [np.nan if '计' not in i else i for i in df['账      号']]
df = df.assign(部门=lst)
df['部门'].fillna(method="bfill",axis=0, inplace=True)
df = df[df['账      号'].str.contains('计') == False] 
pattern = r'(?P<bumen>\w+)小计(?:.*)'
regexp = re.compile(pattern)
repl = lambda m : m.group('bumen')
df['部门'] = df['部门'].str.replace(regexp,repl,regex = True)
index = df.columns.to_list().index('考勤')
# for i in ['绩效','安全分','安全责任基数'	,'安全奖'][::-1]:
#     df.insert(index,i,0)
df.to_excel('lt.xlsx')

In [ ]:
import pandas as pd
import numpy as np
import re
import os

def gongzi(fname,sheet_name):
    df = pd.read_excel(fname,sheet_name = sheet_name,skiprows = 3)
    df = df.loc[~df['姓名'].isnull()]
    df = df.drop(['序号'],axis = 1)
    for i in ['公司','部门'][::-1]:
        df.insert(0,i,'')
    df['公司'] = '双佳'
    df['账      号'] = df['账      号'].fillna('现金')
    df['部门'] = df['账      号']
    df = df[df['账      号'].str.contains('账      号|合计|本页') == False] 
    lst = [np.nan if '计' not in i else i for i in df['账      号']]
    df = df.assign(部门=lst)
    df['部门'].fillna(method="bfill",axis=0, inplace=True)
    df = df[df['账      号'].str.contains('计') == False] 
    pattern = r'(?P<bumen>\w+)小计(?:.*)'
    regexp = re.compile(pattern)
    repl = lambda m : m.group('bumen')
    df['部门'] = df['部门'].str.replace(regexp,repl,regex = True)
    index = df.columns.to_list().index('考勤')
    return df

In [20]:
import pandas as pd
import numpy as np
import re
import os

def gongzi(fname,sheet_name):
    df = pd.read_excel(fname,sheet_name = sheet_name,skiprows = 3)
    df = df.loc[~df['姓名'].isnull()]
    df = df.drop(['序号'],axis = 1)
    for i in ['公司','部门'][::-1]:
        df.insert(0,i,'')
    if '双佳' in fname:
        df['公司'] = '双佳'
    else :
        df['公司'] = '莱特'
    df['账      号'] = df['账      号'].fillna('现金')
    df['部门'] = df['账      号']
    df = df[df['账      号'].str.contains('账      号|合计|本页') == False] 
    lst = [np.nan if '计' not in i else i for i in df['账      号']]
    df = df.assign(部门=lst)
    df['部门'].fillna(method="bfill",axis=0, inplace=True)
    df = df[df['账      号'].str.contains('计') == False] 
    pattern = r'(?P<bumen>\w+)小计(?:.*)'
    regexp = re.compile(pattern)
    repl = lambda m : m.group('bumen')
    df['部门'] = df['部门'].str.replace(regexp,repl,regex = True)
    index = df.columns.to_list().index('考勤')
    return df
    
def main():
    fname_gongzi = r'F:\a00nutstore\008\gongzi\实时工资.xlsx'
    sheet_name_gz = '工资'
    fname = r"F:\repos\fish\新芭案例\工资\莱特工资表.xls"
    sheet_name = r'2024.2'
    path,file = os.path.split(fname)
    os.chdir(path)
    columns_name = ['公司',
                     '部门',
                     '账号',
                     '姓名',
                     '基本工资',
                     '团体奖金',
                     '效益奖金',
                     '话费职补高温',
                     '考勤奖',
                     '加班工资',
                     '考核分数',
                     '考评基数',
                     '消防分数',
                     '消防基数',
                     '计件/考核',
                     '绩效',
                     '安全分',
                     '安全责任基数',
                     '安全奖',
                     '考勤',
                     '奖罚',
                     '其他',
                     '社保',
                     '应发数',
                     '个税',
                     '实发数',
                     '备注',
                     '签名']

    fname_sj = r"F:\repos\fish\新芭案例\工资\双佳工资表.xls"
    sheet_name_sj = r'2024.2' 
    df_sj =  gongzi(fname_sj,sheet_name_sj)
    index = df_sj.columns.to_list().index('考勤')
    for i in ['绩效','安全分','安全责任基数'	,'安全奖'][::-1]:
        df_sj.insert(index,i,0)
    df_sj.columns = columns_name
    
    fname_lt = r"F:\repos\fish\新芭案例\工资\莱特工资表.xls"
    sheet_name_lt = r'2024.2' 
    df_laite =  gongzi(fname_lt,sheet_name_lt)
    df_laite.columns = columns_name

    df = pd.concat([df_sj,df_laite])
    df.index = range(df.shape[0])
    df_laite.to_excel(fname_gongzi,sheet_name = sheet_name_gz,index=False)
    index = df['账号'].to_list().index('6230290032789725')
    df['公司'] = np.where(df.index < index, df['公司'],'物业')
    df.to_excel(fname_gongzi,sheet_name = sheet_name_gz,index = False)
if __name__ == '__main__':
    main()

In [12]:
columns_name = ['公司',
                     '部门',
                     '账号',
                     '姓名',
                     '基本工资',
                     '团体奖金',
                     '效益奖金',
                     '话费职补高温',
                     '考勤奖',
                     '加班工资',
                     '考核分数',
                     '考评基数',
                     '消防分数',
                     '消防基数',
                     '计件/考核',
                     '绩效',
                     '安全分',
                     '安全责任基数',
                     '安全奖',
                     '考勤',
                     '奖罚',
                     '其他',
                     '社保',
                     '应发数',
                     '个税',
                     '实发数',
                     '备注',
                     '签名']
fname_sj = r"F:\repos\fish\新芭案例\工资\双佳工资表.xls"
sheet_name_sj = r'2024.2' 
df_sj =  gongzi(fname_sj,sheet_name_sj)
index = df_sj.columns.to_list().index('考勤')
for i in ['绩效','安全分','安全责任基数'	,'安全奖'][::-1]:
    df_sj.insert(index,i,0)
df_sj.columns = columns_name


fname_lt = r"F:\repos\fish\新芭案例\工资\莱特工资表.xls"
sheet_name_lt = r'2024.2' 
df_laite =  gongzi(fname_lt,sheet_name_lt)
df_laite.columns = columns_name

df = pd.concat([df_sj,df_laite])
df

,公司,部门,账号,姓名,基本工资,团体奖金,效益奖金,话费职补高温,考勤奖,加班工资,...,安全奖,考勤,奖罚,其他,社保,应发数,个税,实发数,备注,签名
0,双佳,行政部,6222627110000141584,张凤英,1600,1200,NaN,NaN,233,81,...,0,NaN,1769,NaN,383,4590,0,4590,奖100、派工1669,NaN
1,双佳,行政部,6222627110000407134,张桂兰,1350,455,600,NaN,163,72,...,0,NaN,NaN,NaN,383,2257,0,2257,NaN,NaN
2,双佳,行政部,6222627110000041065,简翠凤,1350,455,600,NaN,163,NaN,...,0,NaN,NaN,NaN,383,2185,0,2185,NaN,NaN
3,双佳,行政部,6222627110000059349,饶胜利,1600,480,500,960,217,382,...,0,NaN,NaN,NaN,NaN,4139,0,4139,NaN,NaN
4,双佳,行政部,6222627110000914048,梁胜堂,1600,490,500,980,217,346,...,0,NaN,NaN,NaN,383,3750,0,3750,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92,双佳,统计质检部,6230290032789477,夏志艳,1850,809,420,NaN,263,119.3,...,NaN,-30,644,NaN,442,3941,0,3941,介绍400、派工244,NaN
93,双佳,统计质检部,6230290032789683,李敏敏,1850,809,420,100,263,99,...,NaN,NaN,1182,NaN,442,4596,0,4596,车间派工1182,NaN
94,双佳,统计质检部,6230290032789667,胡晶晶,1600,745,420,NaN,NaN,36,...,NaN,-80,270,NaN,442,2710,0,2710,派工200、奖70,NaN
95,双佳,统计质检部,6230290032789436,夏银秀,1600,745,420,NaN,236,36,...,NaN,NaN,410,NaN,442,3320,0,3320,车间派工410,NaN
96,双佳,统计质检部,6230290032789626,周黎明,1600,662,360,NaN,223,36,...,NaN,NaN,424,NaN,442,3185,0,3185,车间派工424,NaN

In [13]:
df.index = range(df.shape[0])
df

,公司,部门,账号,姓名,基本工资,团体奖金,效益奖金,话费职补高温,考勤奖,加班工资,...,安全奖,考勤,奖罚,其他,社保,应发数,个税,实发数,备注,签名
0,双佳,行政部,6222627110000141584,张凤英,1600,1200,NaN,NaN,233,81,...,0,NaN,1769,NaN,383,4590,0,4590,奖100、派工1669,NaN
1,双佳,行政部,6222627110000407134,张桂兰,1350,455,600,NaN,163,72,...,0,NaN,NaN,NaN,383,2257,0,2257,NaN,NaN
2,双佳,行政部,6222627110000041065,简翠凤,1350,455,600,NaN,163,NaN,...,0,NaN,NaN,NaN,383,2185,0,2185,NaN,NaN
3,双佳,行政部,6222627110000059349,饶胜利,1600,480,500,960,217,382,...,0,NaN,NaN,NaN,NaN,4139,0,4139,NaN,NaN
4,双佳,行政部,6222627110000914048,梁胜堂,1600,490,500,980,217,346,...,0,NaN,NaN,NaN,383,3750,0,3750,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84,双佳,统计质检部,6230290032789477,夏志艳,1850,809,420,NaN,263,119.3,...,NaN,-30,644,NaN,442,3941,0,3941,介绍400、派工244,NaN
85,双佳,统计质检部,6230290032789683,李敏敏,1850,809,420,100,263,99,...,NaN,NaN,1182,NaN,442,4596,0,4596,车间派工1182,NaN
86,双佳,统计质检部,6230290032789667,胡晶晶,1600,745,420,NaN,NaN,36,...,NaN,-80,270,NaN,442,2710,0,2710,派工200、奖70,NaN
87,双佳,统计质检部,6230290032789436,夏银秀,1600,745,420,NaN,236,36,...,NaN,NaN,410,NaN,442,3320,0,3320,车间派工410,NaN
88,双佳,统计质检部,6230290032789626,周黎明,1600,662,360,NaN,223,36,...,NaN,NaN,424,NaN,442,3185,0,3185,车间派工424,NaN

In [14]:
sheet_name_gz

In [16]:
index = df['账号'].to_list().index('6230290032789725')
df['公司'] = np.where(df.index < index, df['公司'],'物业')

In [18]:
df.to_excel('222.xlsx',index = False)

In [25]:
import openpyxl
import pandas as pd
import numpy as np
import re
import os


def gongzi(fname,sheet_name):
    df = pd.read_excel(fname,sheet_name = sheet_name,skiprows = 3)
    df = df.loc[~df['姓名'].isnull()]
    df = df.drop(['序号'],axis = 1)
    for i in ['公司','部门'][::-1]:
        df.insert(0,i,'')
    if '双佳' in fname:
        df['公司'] = '双佳'
    else :
        df['公司'] = '莱特'
    df['账      号'] = df['账      号'].fillna('现金')
    df['部门'] = df['账      号']
    df = df[df['账      号'].str.contains('账      号|合计|本页') == False] 
    lst = [np.nan if '计' not in i else i for i in df['账      号']]
    df = df.assign(部门=lst)
    df['部门'].fillna(method="bfill",axis=0, inplace=True)
    df = df[df['账      号'].str.contains('计') == False] 
    pattern = r'(?P<bumen>\w+)小计(?:.*)'
    regexp = re.compile(pattern)
    repl = lambda m : m.group('bumen')
    df['部门'] = df['部门'].str.replace(regexp,repl,regex = True)
    index = df.columns.to_list().index('考勤')
    return df
    
def main():
    fname_gongzi = r'F:\a00nutstore\008\gongzi\实时工资.xlsx'
    sheet_name_gz = '工资'
    fname = r"F:\repos\fish\新芭案例\工资\莱特工资表.xls"
    sheet_name = r'2024.2'
    path,file = os.path.split(fname)
    os.chdir(path)
    columns_name = ['公司',
                     '部门',
                     '账号',
                     '姓名',
                     '基本工资',
                     '团体奖金',
                     '效益奖金',
                     '话费职补高温',
                     '考勤奖',
                     '加班工资',
                     '考核分数',
                     '考评基数',
                     '消防分数',
                     '消防基数',
                     '计件/考核',
                     '绩效',
                     '安全分',
                     '安全责任基数',
                     '安全奖',
                     '考勤',
                     '奖罚',
                     '其他',
                     '社保',
                     '应发数',
                     '个税',
                     '实发数',
                     '备注',
                     '签名']

    fname_sj = r"F:\repos\fish\新芭案例\工资\双佳工资表.xls"
    sheet_name_sj = r'2024.2' 
    df_sj =  gongzi(fname_sj,sheet_name_sj)
    index = df_sj.columns.to_list().index('考勤')
    for i in ['绩效','安全分','安全责任基数'	,'安全奖'][::-1]:
        df_sj.insert(index,i,0)
    df_sj.columns = columns_name
    
    fname_lt = r"F:\repos\fish\新芭案例\工资\莱特工资表.xls"
    sheet_name_lt = r'2024.2' 
    df_laite =  gongzi(fname_lt,sheet_name_lt)
    df_laite.columns = columns_name

    df = pd.concat([df_sj,df_laite])
    df.index = range(df.shape[0])
    df_laite.to_excel(fname_gongzi,sheet_name = sheet_name_gz,index=False)
    index = df['账号'].to_list().index('6230290032789725')
    df['公司'] = np.where(df.index < index, df['公司'],'物业')
    # with pd.ExcelWriter(fname_gongzi,engine='openpyxl',date_format='yyyy-mm-dd',mode='a', if_sheet_exists='overlay')  as writer:
    #     df.to_excel(writer, sheet_name_gz, index=False)
    # with pd.ExcelWriter(fname_gongzi) as writer:
    #     df.to_excel(writer, sheet_name_gz, index=False)
    #     wb = openpyxl.load_workbook(fname_ruku)
    wb = openpyxl.load_work(fname_gongzi)
    ws=wb[sheet_name_gz]
    ws.delete_rows(1,10000)
    with pd.ExcelWriter(fname_gongzi, engine='openpyxl')  as writer:
        writer.book = wb
        writer.sheets = dict((ws.title, ws) for ws in wb.worksheets)
        df.to_excel(writer, fname_gongzi, index=False, startrow= 1)
    writer.save()

      
    # df.to_excel(fname_gongzi,sheet_name = sheet_name_gz,index = False)
if __name__ == '__main__':
    main()

In [1]:
df_laite =  gongzi(fname_lt,sheet_name = None)
list(df_laite)

NameError: name 'gongzi' is not defined

In [4]:

import panda as pd
fname_sj = r"F:\repos\fish\新芭案例\工资\双佳工资表.xls"
df_sj =  pd.read_excel(fname_sj,sheet_name=None)
list(df_laite)

ModuleNotFoundError: No module named 'panda'

In [13]:
import pandas as pd
fname = r"F:\repos\fish\新芭案例\工资\莱特工资表.xls"
sheet_name = r'2024.2'
df =  pd.read_excel(fname,sheet_name=sheet_name)
df

,武 汉 莱 特 纸 品 有 限 公 司,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26
0,工 资 表,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024-02-25 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,序号,账 号,姓名,基本工资,团体奖金,效益奖金,话费补贴,考勤奖,加班工资,考核分数,...,安全奖,考勤,奖罚,其他,社保,应发数,个税,实发数,备注,签名
3,1,6213611001001604620,罗国勇,2850,1214,680,NaN,NaN,NaN,0.92,...,0,NaN,NaN,NaN,455,4289,0,4289,NaN,NaN
4,2,6230334001006340972,陈永芳,2550,1002,560,50,NaN,NaN,0.92,...,0,NaN,NaN,NaN,442,3720,0,3720,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98,6,6230290032789436,夏银秀,1600,745,420,NaN,236,36,0.92,...,NaN,NaN,410,NaN,442,3320,0,3320,车间派工410,NaN
99,7,6230290032789626,周黎明,1600,662,360,NaN,223,36,0.92,...,NaN,NaN,424,NaN,442,3185,0,3185,车间派工424,NaN
100,NaN,统计质检部小计：（人）,7,13800,5959,3260,300,1726,486.3,6.44,...,0,-110,3056,0,3166,27057,0,27057,NaN,0
101,NaN,本页小计：（人）,20,45350,19491,10480,1040,5406,1327.3,18.58,...,817,-315.2,4791,0,9344,84809,38,84771,NaN,NaN
102,NaN,核准:,NaN,NaN,NaN,复核:,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,制表:,戴玲,NaN,NaN,NaN

In [14]:
skiprows = df.iloc[:,2].to_list().index('姓名') + 1
skiprows

3

In [15]:
sheetname = '2024.1'
year,month = sheetname.split('.')
year

'2024'

In [16]:
month

'1'

In [1]:
import pandas as pd

In [4]:
fname1 = r"F:\a00nutstore\008\gongzi\实时工资2024-02.xlsx"
sheet_name1 = '工资'
df1 = pd.read_excel(fname1,sheet_name1)
df1

,公司,部门,账号,姓名,基本工资,团体奖金,效益奖金,话费职补高温,考勤奖,加班工资,...,安全奖,考勤,奖罚,其他,社保,应发数,个税,实发数,备注,签名
0,双佳,财务部,6222627110001057029,戴玲,2200,892.0,480.0,50.0,304.0,NaN,...,0.0,NaN,NaN,NaN,383.0,3543,0,3543,NaN,NaN
1,双佳,财务部,6222627110001342215,晏梦琪,1850,809.0,420.0,50.0,NaN,NaN,...,0.0,-120.0,NaN,NaN,383.0,2626,0,2626,NaN,NaN
2,物业,采购部,6230290032789758,刘西,1750,765.0,400.0,100.0,250.0,81.0,...,NaN,-5.2,NaN,NaN,442.0,2898,0,2898,NaN,NaN
3,双佳,仓库搬运,6222627110000041248,江小珍,2150,892.0,480.0,NaN,300.0,140.0,...,0.0,NaN,NaN,NaN,383.0,3579,0,3579,NaN,NaN
4,双佳,仓库搬运,6222627110000040992,葛翠平,2100,892.0,480.0,NaN,296.0,36.0,...,0.0,NaN,1159.0,NaN,383.0,4580,0,4580,车间派工1159,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84,双佳,营销部,6222627110000367338,刘威,2050,800.0,1350.0,100.0,NaN,NaN,...,0.0,NaN,NaN,NaN,383.0,3917,0,3917,NaN,NaN
85,双佳,营销部,6222627110001021843,张红飞,1850,800.0,1250.0,100.0,NaN,NaN,...,0.0,NaN,NaN,NaN,383.0,3617,0,3617,NaN,NaN
86,双佳,营销部,6222627110001377526,徐浩,1650,950.0,1200.0,50.0,NaN,NaN,...,0.0,NaN,NaN,NaN,383.0,3467,0,3467,NaN,NaN
87,双佳,营销部,6222627110000407803,高婷,1750,782.0,400.0,50.0,NaN,36.0,...,0.0,NaN,NaN,NaN,383.0,2635,0,2635,NaN,NaN
88,双佳,营销部,6222627110000535512,黄茜,1900,837.0,440.0,NaN,NaN,36.0,...,0.0,-30.0,NaN,NaN,383.0,2800,0,2800,NaN,NaN

In [6]:
fname2 = r"F:\a00nutstore\008\gongzi\实时工资.xlsx"
sheet_name1 = '工资'
df2 = pd.read_excel(fname2,sheet_name1)
df2

,公司,部门,账号,姓名,基本工资,团体奖金,效益奖金,话费职补高温,考勤奖,加班工资,...,安全奖,考勤,奖罚,其他,社保,应发数,个税,实发数,备注,签名
0,双佳,行政部,6222627110000141584,张凤英,1600.0,1200.0,NaN,NaN,233.0,257.0,...,0.0,NaN,3294.0,NaN,383.0,6291,39.0,6252,派工2694、全勤500,NaN
1,双佳,行政部,6222627110000407134,张桂兰,1350.0,600.0,NaN,NaN,163.0,144.0,...,0.0,NaN,1342.0,NaN,383.0,3216,0.0,3216,车间派工887,NaN
2,双佳,行政部,6222627110000041065,简翠凤,1350.0,600.0,NaN,NaN,163.0,108.0,...,0.0,NaN,1216.0,NaN,383.0,3054,0.0,3054,车间派工761,NaN
3,双佳,行政部,6222627110000059349,饶胜利,1600.0,500.0,500.0,1260.0,217.0,502.0,...,0.0,NaN,NaN,NaN,NaN,4579,0.0,4579,NaN,NaN
4,双佳,行政部,6222627110000914048,梁胜堂,1600.0,500.0,500.0,1680.0,217.0,400.0,...,0.0,NaN,NaN,NaN,383.0,4514,0.0,4514,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85,物业,统计质检部,6230290032789477,夏志艳,1850.0,809.0,420.0,NaN,263.0,212.0,...,NaN,NaN,1206.0,NaN,442.0,4687,0.0,4687,车间派工1206,NaN
86,物业,统计质检部,6230290032789683,李敏敏,1850.0,809.0,420.0,100.0,263.0,182.3,...,NaN,-24.0,1549.0,NaN,442.0,5116,3.0,5113,车间派工1549,NaN
87,物业,统计质检部,6230290032789667,胡晶晶,1600.0,745.0,420.0,NaN,236.0,108.0,...,NaN,-40.0,286.0,NaN,442.0,3115,0.0,3115,车间派工286,NaN
88,物业,统计质检部,6230290032789436,夏银秀,1600.0,745.0,420.0,NaN,236.0,72.0,...,NaN,NaN,709.0,NaN,442.0,3745,0.0,3745,派工209、全勤500,NaN
89,物业,统计质检部,6230290032789626,周黎明,1600.0,662.0,360.0,NaN,223.0,108.0,...,NaN,NaN,741.0,NaN,442.0,3675,0.0,3675,派工241、全勤500,NaN

In [10]:
with pd.ExcelWriter(fname2, engine='openpyxl',date_format='yyyy-m-d', mode='a', if_sheet_exists='overlay') as writer:
    df1.to_excel(writer, sheet_name1, index=False)