In [1]:
import pandas as pd

In [2]:
df = pd.read_clipboard()
df

                   原始数据                            新增数据
0        (新股,7),(石油气,6)                          新股,石油气
1            拟收购,新能源,医药               新股,石油气,拟收购,新能源,医药
2               军工,业绩预增       新股,石油气,拟收购,新能源,医药,军工,业绩预增
3               乡村振兴,有色      拟收购,新能源,医药,军工,业绩预增,乡村振兴,有色
4                 医药,军工           军工,业绩预增,乡村振兴,有色,医药,军工
5  (物流,3),(环保,2),(芯片,1)          乡村振兴,有色,医药,军工,物流,环保,芯片
6                高送转,妖股           医药,军工,物流,环保,芯片,高送转,妖股
7              中标,工业4.0        物流,环保,芯片,高送转,妖股,中标,工业4.0
8  (消费,5),(金融,4),(券商,3)        高送转,妖股,中标,工业4.0,消费,金融,券商
9          5G,汽车,国资,房地产  中标,工业4.0,消费,金融,券商,5G,汽车,国资,房地产

In [10]:
foo = (
       df.原始数据
         .replace(r',','=',regex = True)
         .replace(r'\)=\(',',',regex = True)
        .map(lambda x:eval(f'dict{x}') if '(' in x else {})
)
foo

0            {'新股': 7, '石油气': 6}
1                             {}
2                             {}
3                             {}
4                             {}
5    {'物流': 3, '环保': 2, '芯片': 1}
6                             {}
7                             {}
8    {'消费': 5, '金融': 4, '券商': 3}
9                             {}
Name: 原始数据, dtype: object

In [14]:
(
 df.assign(foo = foo)
   .assign(bar= df.新增数据.str.split(','))
   .assign(total = lambda d:d.apply(lambda s:sum(s.foo[i] for i in s.bar if i in s.foo),axis = 1))
   )

,原始数据,新增数据,foo,bar,total
0,"(新股,7),(石油气,6)","新股,石油气","{'新股': 7, '石油气': 6}","[新股, 石油气]",13
1,"拟收购,新能源,医药","新股,石油气,拟收购,新能源,医药",{},"[新股, 石油气, 拟收购, 新能源, 医药]",0
2,"军工,业绩预增","新股,石油气,拟收购,新能源,医药,军工,业绩预增",{},"[新股, 石油气, 拟收购, 新能源, 医药, 军工, 业绩预增]",0
3,"乡村振兴,有色","拟收购,新能源,医药,军工,业绩预增,乡村振兴,有色",{},"[拟收购, 新能源, 医药, 军工, 业绩预增, 乡村振兴, 有色]",0
4,"医药,军工","军工,业绩预增,乡村振兴,有色,医药,军工",{},"[军工, 业绩预增, 乡村振兴, 有色, 医药, 军工]",0
5,"(物流,3),(环保,2),(芯片,1)","乡村振兴,有色,医药,军工,物流,环保,芯片","{'物流': 3, '环保': 2, '芯片': 1}","[乡村振兴, 有色, 医药, 军工, 物流, 环保, 芯片]",6
6,"高送转,妖股","医药,军工,物流,环保,芯片,高送转,妖股",{},"[医药, 军工, 物流, 环保, 芯片, 高送转, 妖股]",0
7,"中标,工业4.0","物流,环保,芯片,高送转,妖股,中标,工业4.0",{},"[物流, 环保, 芯片, 高送转, 妖股, 中标, 工业4.0]",0
8,"(消费,5),(金融,4),(券商,3)","高送转,妖股,中标,工业4.0,消费,金融,券商","{'消费': 5, '金融': 4, '券商': 3}","[高送转, 妖股, 中标, 工业4.0, 消费, 金融, 券商]",12
9,"5G,汽车,国资,房地产","中标,工业4.0,消费,金融,券商,5G,汽车,国资,房地产",{},"[中标, 工业4.0, 消费, 金融, 券商, 5G, 汽车, 国资, 房地产]",0

In [18]:
def getSum(s,d):
    x = s.foo
    if len(x) != 0:
        y = sum(x.values())
    else :
        y = 0
    return y

In [20]:
df1 = df.assign(foo = foo).assign(bar= df.新增数据.str.split(','))
df1

,原始数据,新增数据,foo,bar
0,"(新股,7),(石油气,6)","新股,石油气","{'新股': 7, '石油气': 6}","[新股, 石油气]"
1,"拟收购,新能源,医药","新股,石油气,拟收购,新能源,医药",{},"[新股, 石油气, 拟收购, 新能源, 医药]"
2,"军工,业绩预增","新股,石油气,拟收购,新能源,医药,军工,业绩预增",{},"[新股, 石油气, 拟收购, 新能源, 医药, 军工, 业绩预增]"
3,"乡村振兴,有色","拟收购,新能源,医药,军工,业绩预增,乡村振兴,有色",{},"[拟收购, 新能源, 医药, 军工, 业绩预增, 乡村振兴, 有色]"
4,"医药,军工","军工,业绩预增,乡村振兴,有色,医药,军工",{},"[军工, 业绩预增, 乡村振兴, 有色, 医药, 军工]"
5,"(物流,3),(环保,2),(芯片,1)","乡村振兴,有色,医药,军工,物流,环保,芯片","{'物流': 3, '环保': 2, '芯片': 1}","[乡村振兴, 有色, 医药, 军工, 物流, 环保, 芯片]"
6,"高送转,妖股","医药,军工,物流,环保,芯片,高送转,妖股",{},"[医药, 军工, 物流, 环保, 芯片, 高送转, 妖股]"
7,"中标,工业4.0","物流,环保,芯片,高送转,妖股,中标,工业4.0",{},"[物流, 环保, 芯片, 高送转, 妖股, 中标, 工业4.0]"
8,"(消费,5),(金融,4),(券商,3)","高送转,妖股,中标,工业4.0,消费,金融,券商","{'消费': 5, '金融': 4, '券商': 3}","[高送转, 妖股, 中标, 工业4.0, 消费, 金融, 券商]"
9,"5G,汽车,国资,房地产","中标,工业4.0,消费,金融,券商,5G,汽车,国资,房地产",{},"[中标, 工业4.0, 消费, 金融, 券商, 5G, 汽车, 国资, 房地产]"

In [22]:
df1.assign(total = lambda x:x.apply(getSum,d=df1,axis = 1))

,原始数据,新增数据,foo,bar,total
0,"(新股,7),(石油气,6)","新股,石油气","{'新股': 7, '石油气': 6}","[新股, 石油气]",13
1,"拟收购,新能源,医药","新股,石油气,拟收购,新能源,医药",{},"[新股, 石油气, 拟收购, 新能源, 医药]",0
2,"军工,业绩预增","新股,石油气,拟收购,新能源,医药,军工,业绩预增",{},"[新股, 石油气, 拟收购, 新能源, 医药, 军工, 业绩预增]",0
3,"乡村振兴,有色","拟收购,新能源,医药,军工,业绩预增,乡村振兴,有色",{},"[拟收购, 新能源, 医药, 军工, 业绩预增, 乡村振兴, 有色]",0
4,"医药,军工","军工,业绩预增,乡村振兴,有色,医药,军工",{},"[军工, 业绩预增, 乡村振兴, 有色, 医药, 军工]",0
5,"(物流,3),(环保,2),(芯片,1)","乡村振兴,有色,医药,军工,物流,环保,芯片","{'物流': 3, '环保': 2, '芯片': 1}","[乡村振兴, 有色, 医药, 军工, 物流, 环保, 芯片]",6
6,"高送转,妖股","医药,军工,物流,环保,芯片,高送转,妖股",{},"[医药, 军工, 物流, 环保, 芯片, 高送转, 妖股]",0
7,"中标,工业4.0","物流,环保,芯片,高送转,妖股,中标,工业4.0",{},"[物流, 环保, 芯片, 高送转, 妖股, 中标, 工业4.0]",0
8,"(消费,5),(金融,4),(券商,3)","高送转,妖股,中标,工业4.0,消费,金融,券商","{'消费': 5, '金融': 4, '券商': 3}","[高送转, 妖股, 中标, 工业4.0, 消费, 金融, 券商]",12
9,"5G,汽车,国资,房地产","中标,工业4.0,消费,金融,券商,5G,汽车,国资,房地产",{},"[中标, 工业4.0, 消费, 金融, 券商, 5G, 汽车, 国资, 房地产]",0