In [1]:
import pandas as pd

In [22]:
df = pd.read_clipboard()
df

,日期,供货单位,kun7/16,kun9/16,tiao5/16,tiao3/8,tiao7/16,tiao1/2,tiao9/16,tiao5/8,tiao3/4,tiao7/8,tiao1,tiaoQ14,tiaoQ12,tiaoQ10
0,2021-5-26,彩皇,170,187,0.00340,0.0040,0.00550,0.00640,0.00860,0.01160,0.01600,0.02130,0.0340,0.00437,0.003875,0.00270
1,2021-11-3,彩皇,170,187,0.00374,0.0044,0.00605,0.00704,0.00946,0.01276,0.01265,0.02343,0.0374,0.00502,0.004460,0.00474

In [26]:
df = df.astype({'日期':'datetime64'})
df

,日期,供货单位,kun7/16,kun9/16,tiao5/16,tiao3/8,tiao7/16,tiao1/2,tiao9/16,tiao5/8,tiao3/4,tiao7/8,tiao1,tiaoQ14,tiaoQ12,tiaoQ10
0,2021-05-26,彩皇,170,187,0.00340,0.0040,0.00550,0.00640,0.00860,0.01160,0.01600,0.02130,0.0340,0.00437,0.003875,0.00270
1,2021-11-03,彩皇,170,187,0.00374,0.0044,0.00605,0.00704,0.00946,0.01276,0.01265,0.02343,0.0374,0.00502,0.004460,0.00474

In [28]:
df = df.set_index('日期')
df

,供货单位,kun7/16,kun9/16,tiao5/16,tiao3/8,tiao7/16,tiao1/2,tiao9/16,tiao5/8,tiao3/4,tiao7/8,tiao1,tiaoQ14,tiaoQ12,tiaoQ10
日期,,,,,,,,,,,,,,,
2021-05-26,彩皇,170,187,0.00340,0.0040,0.00550,0.00640,0.00860,0.01160,0.01600,0.02130,0.0340,0.00437,0.003875,0.00270
2021-11-03,彩皇,170,187,0.00374,0.0044,0.00605,0.00704,0.00946,0.01276,0.01265,0.02343,0.0374,0.00502,0.004460,0.00474

In [19]:
fname = r'F:\a00nutstore\006\zw\price\线圈合同价格.xlsx'
sheet_name = '合同单价'
df = pd.read_excel(fname, sheet_name, index_col=0)
df

,供货单位,kun7/16,kun9/16,tiao5/16,tiao3/8,tiao7/16,tiao1/2,tiao9/16,tiao5/8,tiao3/4,tiao7/8,tiao1,tiaoQ14,tiaoQ12,tiaoQ10
日期,,,,,,,,,,,,,,,
2021-05-26,彩皇,170,187,0.00340,0.0040,0.00550,0.00640,0.00860,0.01160,0.01600,0.02130,0.0340,0.00437,0.003875,0.00270
2021-11-03,彩皇,170,187,0.00374,0.0044,0.00605,0.00704,0.00946,0.01276,0.01265,0.02343,0.0374,0.00502,0.004460,0.00474

In [29]:
end_riqi = pd.Timestamp('2022-8-17')
grouped = df.groupby('供货单位')
all_values = []
for gys, values in grouped:
    last_day = pd.Timestamp(end_riqi)
    values.loc[last_day, '供货单位'] = gys
    values = values.resample('D').ffill()
    values.fillna(method='ffill', inplace=True)
    all_values.append(values)
df2 = pd.concat(all_values, axis=0)
df2

,供货单位,kun7/16,kun9/16,tiao5/16,tiao3/8,tiao7/16,tiao1/2,tiao9/16,tiao5/8,tiao3/4,tiao7/8,tiao1,tiaoQ14,tiaoQ12,tiaoQ10
日期,,,,,,,,,,,,,,,
2021-05-26,彩皇,170.0,187.0,0.00340,0.0040,0.00550,0.00640,0.00860,0.01160,0.01600,0.02130,0.0340,0.00437,0.003875,0.00270
2021-05-27,彩皇,170.0,187.0,0.00340,0.0040,0.00550,0.00640,0.00860,0.01160,0.01600,0.02130,0.0340,0.00437,0.003875,0.00270
2021-05-28,彩皇,170.0,187.0,0.00340,0.0040,0.00550,0.00640,0.00860,0.01160,0.01600,0.02130,0.0340,0.00437,0.003875,0.00270
2021-05-29,彩皇,170.0,187.0,0.00340,0.0040,0.00550,0.00640,0.00860,0.01160,0.01600,0.02130,0.0340,0.00437,0.003875,0.00270
2021-05-30,彩皇,170.0,187.0,0.00340,0.0040,0.00550,0.00640,0.00860,0.01160,0.01600,0.02130,0.0340,0.00437,0.003875,0.00270
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-08-13,彩皇,170.0,187.0,0.00374,0.0044,0.00605,0.00704,0.00946,0.01276,0.01265,0.02343,0.0374,0.00502,0.004460,0.00474
2022-08-14,彩皇,170.0,187.0,0.00374,0.0044,0.00605,0.00704,0.00946,0.01276,0.01265,0.02343,0.0374,0.00502,0.004460,0.00474
2022-08-15,彩皇,170.0,187.0,0.00374,0.0044,0.00605,0.00704,0.00946,0.01276,0.01265,0.02343,0.0374,0.00502,0.004460,0.00474
2022-08-16,彩皇,170.0,187.0,0.00374,0.0044,0.00605,0.00704,0.00946,0.01276,0.01265,0.02343,0.0374,0.00502,0.004460,0.00474
2022-08-17,彩皇,170.0,187.0,0.00374,0.0044,0.00605,0.00704,0.00946,0.01276,0.01265,0.02343,0.0374,0.00502,0.004460,0.00474