In [ ]:
#原材料出库凭证模板生成脚本
#凭证导入导出完整：路径C:\UFSMART\T3系统工具\Excel\导入导出文件.凭证.xls
#引入引出凭证入口：T3系列管理软件\T3\T3系列工具\数据导入导出

In [1]:
import pandas as pd
import xlwings as xw
import easygui
import os

In [2]:
# msg = '请点选原材料出库文件"原材料出库2022-07.xlsx"'
# fname1 = easygui.fileopenbox(msg)
fname1 = r'F:\a00nutstore\006\zw\2022\202207\原材料出库2022-07.xlsx'
df1 = pd.read_excel(fname1) 
df1

          科目编码      科目名称        出库          单价          金额
0   1403001001   70g双胶大度     -14.0  186.426548    -2609.97
1   1403001005   98g双胶正度      34.0  240.168142     8165.72
2   1403001008   74g双胶正度     200.0  185.613115    37122.62
3   1403001013   80g双胶正度     504.0  189.784969    95651.62
4   1403001015  100g双胶正度      34.0  245.080378     8332.73
..         ...       ...       ...         ...         ...
84  1403006008        胶套  332762.0    0.509542   169556.22
85  1403006009       空白袋  522500.0    0.049371    25796.52
86  1403006010        书套   14100.0    0.046190      651.28
87     包装物  小计       NaN       NaN         NaN   435611.06
88         原材料        合计       NaN         NaN  7657598.12

[89 rows x 5 columns]

In [3]:
path,file = os.path.splitext(fname1)
qijian = int(path.split('-')[-1])

In [4]:
qijian

7

In [5]:
df2 = df1.loc[df1['科目名称'] != '合计' ]
df2

          科目编码      科目名称        出库          单价         金额
0   1403001001   70g双胶大度     -14.0  186.426548   -2609.97
1   1403001005   98g双胶正度      34.0  240.168142    8165.72
2   1403001008   74g双胶正度     200.0  185.613115   37122.62
3   1403001013   80g双胶正度     504.0  189.784969   95651.62
4   1403001015  100g双胶正度      34.0  245.080378    8332.73
..         ...       ...       ...         ...        ...
83  1403006007       缠绕膜      44.0   46.036087    2025.59
84  1403006008        胶套  332762.0    0.509542  169556.22
85  1403006009       空白袋  522500.0    0.049371   25796.52
86  1403006010        书套   14100.0    0.046190     651.28
87     包装物  小计       NaN       NaN         NaN  435611.06

[88 rows x 5 columns]

In [8]:
title = ['会计期间',
 '凭证类别字',
 '凭证类别排序号',
 '凭证编号',
 '行号',
 '制单日期',
 '附单据数',
 '制单人',
 '审核人',
 '记账人',
 '记账标志',
 '出纳人',
 '凭证标志',
 '凭证头自定义项1',
 '凭证头自定义项2',
 '摘要',
 '科目编码',
 '币种',
 '借方金额',
 '贷方金额',
 '外币借方金额',
 '外币贷方金额',
 '汇率',
 '数量借方',
 '数量贷方',
 '结算方式编码',
 '票号',
 '票号发生日期',
 '部门编码',
 '职员编码',
 '客户编码',
 '供应商编码',
 '项目编码',
 '项目大类编码',
 '业务员',
 '对方科目编码',
 '银行帐两清标志',
 '往来帐两清标志',
 '是否核销',
 '外部凭证帐套号',
 '外部凭证会计年度',
 '外部凭证系统名称',
 '外部凭证系统版本号',
 '外部凭证制单日期',
 '外部凭证会计期间',
 '外部凭证业务类型',
 '外部凭证业务号',
 '日期',
 '标志',
 '外部凭证单据号',
 '凭证是否可修改',
 '凭证分录是否可增删',
 '凭证合计金额是否保值',
 '分录数值是否可修改',
 '分录科目是否可修改',
 '分录受控科目可用状态',
 '分录往来项是否可修改',
 '分录部门是否可修改',
 '分录项目是否可修改',
 '分录往来项是否必输',
 '自定义字段1',
 '自定义字段2',
 '自定义字段3',
 '自定义字段4',
 '自定义字段5',
 '自定义字段6',
 '自定义字段7',
 '自定义字段8',
 '自定义字段9',
 '自定义字段10',
 '现金项目编号',
 '现金借方',
 '现金贷方']

In [9]:
hanghao = len(df2)
hanghao

88

In [10]:
df_pinzhen = pd.DataFrame(columns = title)
df_pinzhen

Empty DataFrame
Columns: [会计期间, 凭证类别字, 凭证类别排序号, 凭证编号, 行号, 制单日期, 附单据数, 制单人, 审核人, 记账人, 记账标志, 出纳人, 凭证标志, 凭证头自定义项1, 凭证头自定义项2, 摘要, 科目编码, 币种, 借方金额, 贷方金额, 外币借方金额, 外币贷方金额, 汇率, 数量借方, 数量贷方, 结算方式编码, 票号, 票号发生日期, 部门编码, 职员编码, 客户编码, 供应商编码, 项目编码, 项目大类编码, 业务员, 对方科目编码, 银行帐两清标志, 往来帐两清标志, 是否核销, 外部凭证帐套号, 外部凭证会计年度, 外部凭证系统名称, 外部凭证系统版本号, 外部凭证制单日期, 外部凭证会计期间, 外部凭证业务类型, 外部凭证业务号, 日期, 标志, 外部凭证单据号, 凭证是否可修改, 凭证分录是否可增删, 凭证合计金额是否保值, 分录数值是否可修改, 分录科目是否可修改, 分录受控科目可用状态, 分录往来项是否可修改, 分录部门是否可修改, 分录项目是否可修改, 分录往来项是否必输, 自定义字段1, 自定义字段2, 自定义字段3, 自定义字段4, 自定义字段5, 自定义字段6, 自定义字段7, 自定义字段8, 自定义字段9, 自定义字段10, 现金项目编号, 现金借方, 现金贷方]
Index: []

[0 rows x 73 columns]

In [11]:
df_pinzhen['行号'] = range(1,hanghao+1)

In [12]:
fixed_fields = { '凭证类别字':'记',
 '凭证类别排序号':1,
 '附单据数':-1,
 '制单人':'张文伟',
 '数量借方':0,
 '是否核销':0,
 '外部凭证单据号':0,
 '凭证是否可修改':1,
 '凭证分录是否可增删':0,
 '凭证合计金额是否保值':0,
 '分录数值是否可修改':1,
 '分录科目是否可修改':1,
 '分录受控科目可用状态':1,
 '分录往来项是否可修改':1,
 '分录部门是否可修改':1,
 '分录项目是否可修改':1,
 '分录往来项是否必输':0
               }
fixed_fields

{'凭证类别字': '记',
 '凭证类别排序号': 1,
 '附单据数': -1,
 '制单人': '张文伟',
 '数量借方': 0,
 '是否核销': 0,
 '外部凭证单据号': 0,
 '凭证是否可修改': 1,
 '凭证分录是否可增删': 0,
 '凭证合计金额是否保值': 0,
 '分录数值是否可修改': 1,
 '分录科目是否可修改': 1,
 '分录受控科目可用状态': 1,
 '分录往来项是否可修改': 1,
 '分录部门是否可修改': 1,
 '分录项目是否可修改': 1,
 '分录往来项是否必输': 0}

In [13]:
for k,v in fixed_fields.items():
#     print('k',k)
#     print('v',v)
    df_pinzhen[k] = v
df_pinzhen

,会计期间,凭证类别字,凭证类别排序号,凭证编号,行号,制单日期,附单据数,制单人,审核人,记账人,...,自定义字段4,自定义字段5,自定义字段6,自定义字段7,自定义字段8,自定义字段9,自定义字段10,现金项目编号,现金借方,现金贷方
0,NaN,记,1,NaN,1,NaN,-1,张文伟,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,记,1,NaN,2,NaN,-1,张文伟,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,记,1,NaN,3,NaN,-1,张文伟,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,记,1,NaN,4,NaN,-1,张文伟,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,记,1,NaN,5,NaN,-1,张文伟,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,NaN,记,1,NaN,84,NaN,-1,张文伟,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84,NaN,记,1,NaN,85,NaN,-1,张文伟,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
85,NaN,记,1,NaN,86,NaN,-1,张文伟,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
86,NaN,记,1,NaN,87,NaN,-1,张文伟,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
87,NaN,记,1,NaN,88,NaN,-1,张文伟,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
df_pinzhen['会计期间'] = qijian
df_pinzhen

,会计期间,凭证类别字,凭证类别排序号,凭证编号,行号,制单日期,附单据数,制单人,审核人,记账人,...,自定义字段4,自定义字段5,自定义字段6,自定义字段7,自定义字段8,自定义字段9,自定义字段10,现金项目编号,现金借方,现金贷方
0,7,记,1,NaN,1,NaN,-1,张文伟,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,7,记,1,NaN,2,NaN,-1,张文伟,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,7,记,1,NaN,3,NaN,-1,张文伟,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,7,记,1,NaN,4,NaN,-1,张文伟,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,7,记,1,NaN,5,NaN,-1,张文伟,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,7,记,1,NaN,84,NaN,-1,张文伟,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84,7,记,1,NaN,85,NaN,-1,张文伟,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
85,7,记,1,NaN,86,NaN,-1,张文伟,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
86,7,记,1,NaN,87,NaN,-1,张文伟,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
87,7,记,1,NaN,88,NaN,-1,张文伟,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df_pinzhen.to_excel('111.xlsx',index = False)
os.startfile('111.xlsx')

In [15]:
dic = {'纸  小计':'5001002',
      '灰板  小计':'5001003',
      '辅料  小计':'5001004',
      '包装物  小计':'5001006'}

In [16]:
def func(dic,s):
    s1 = []
    for i in s:
        j = dic.get(i.strip(),i)
        s1.append(j)
    return s1

In [17]:
kemubianma = func(dic,df2['科目编码'].to_list())

kemubianma

['1403001001',
 '1403001005',
 '1403001008',
 '1403001013',
 '1403001015',
 '1403001016',
 '1403001026',
 '1403001027',
 '1403001028',
 '1403001029',
 '1403001030',
 '1403001033',
 '1403001045',
 '1403001047',
 '1403001048',
 '1403001101',
 '1403001105',
 '1403001108',
 '1403001109',
 '1403001118',
 '1403001121',
 '1403001122',
 '1403001125',
 '1403001126',
 '1403001129',
 '1403001130',
 '1403001138',
 '1403001140',
 '1403001159',
 '1403001160',
 '1403001203',
 '1403001204',
 '1403001205',
 '1403001206',
 '1403001301',
 '1403001302',
 '1403001303',
 '1403001304',
 '1403001305',
 '1403001306',
 '1403001318',
 '1403001401',
 '1403001402',
 '1403001405',
 '1403001406',
 '1403001411',
 '1403001412',
 '1403001501',
 '1403001503',
 '1403001507',
 '1403001514',
 '1403001518',
 '5001002',
 '1403002002',
 '1403002004',
 '1403002006',
 '1403002007',
 '1403002022',
 '5001003',
 '1403003001',
 '1403003002',
 '1403003003',
 '1403003004',
 '1403003005',
 '1403003013',
 '1403003015',
 '1403003018',
 '1403003019',
 '1403003021',
 '1403003022',
 '1403003027',
 '1403003028',
 '1403003031',
 '1403003033',
 '1403003034',
 '1403003036',
 '1403003037',
 '5001004',
 '1403006001',
 '1403006002',
 '1403006003',
 '1403006004',
 '1403006005',
 '1403006007',
 '1403006008',
 '1403006009',
 '1403006010',
 '5001006']

In [18]:
df_pinzhen['科目编码'] = kemubianma
df_pinzhen

,会计期间,凭证类别字,凭证类别排序号,凭证编号,行号,制单日期,附单据数,制单人,审核人,记账人,...,自定义字段4,自定义字段5,自定义字段6,自定义字段7,自定义字段8,自定义字段9,自定义字段10,现金项目编号,现金借方,现金贷方
0,7,记,1,NaN,1,NaN,-1,张文伟,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,7,记,1,NaN,2,NaN,-1,张文伟,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,7,记,1,NaN,3,NaN,-1,张文伟,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,7,记,1,NaN,4,NaN,-1,张文伟,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,7,记,1,NaN,5,NaN,-1,张文伟,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,7,记,1,NaN,84,NaN,-1,张文伟,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84,7,记,1,NaN,85,NaN,-1,张文伟,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
85,7,记,1,NaN,86,NaN,-1,张文伟,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
86,7,记,1,NaN,87,NaN,-1,张文伟,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
87,7,记,1,NaN,88,NaN,-1,张文伟,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
def jiner(kemu,jiner):
    jie = []
    dai = []
    for kemu,i in zip(kemu,jiner):
        if '计' in kemu:
            jie.append(i)
            dai.append(0)
        else :
            dai.append(i)
            jie.append(0)
    return jie,dai

In [20]:
jie,dai = jiner(df2['科目编码'],df2['金额'])
jie,dai

([0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  6942134.9,
  0,
  0,
  0,
  0,
  0,
  62798.61,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  217053.55,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  435611.0599999999],
 [-2609.97,
  8165.72,
  37122.62,
  95651.62,
  8332.73,
  13149.89,
  69784.5,
  16176.55,
  461.13,
  35851.05,
  5371.36,
  -1800.0,
  27936.03,
  3489.84,
  7408.88,
  11640.95,
  26641.65,
  2829.74,
  77.16,
  120975.67,
  34469.67,
  17328.99,
  28392.12,
  24772.18,
  90825.0,
  7853.14,
  3577.35,
  9839.87,
  4128.32,
  1925.15,
  16334.32,
  13365.65,
  33460.36,
  4675.88,
  61993.83,
  302654.57,
  27269.06,
  16148.02,
  8417.9,
  1558.61,
  3674.79,
  5109.11,
  23378.29,
  7544.14,
  10867.96,
  36955.94,
  17820.79,
  5401043.68,
  57788.72,
  18147.5,
  149394.54,
  14762.33,
  0,
  33466.88,
  1967.8,
  10051.03,
  11272.25,
  6040.65,
  0,
  8849.52,
  7329.03,
  4161.35,
  80512.37,
  902.92,
  27259.41,
  4086.83,
  6647.6,
  276.42,
  33814.55,
  6815.94,
  451.61,
  5348.49,
  21277.3,
  785.63,
  2532.5,
  5522.09,
  479.99,
  0,
  3933.86,
  179013.22,
  53.26,
  39800.53,
  14780.58,
  2025.59,
  169556.22,
  25796.52,
  651.28,
  0])

In [21]:
df_pinzhen['借方金额'] = jie
df_pinzhen['贷方金额'] = dai

In [22]:
df_pinzhen

,会计期间,凭证类别字,凭证类别排序号,凭证编号,行号,制单日期,附单据数,制单人,审核人,记账人,...,自定义字段4,自定义字段5,自定义字段6,自定义字段7,自定义字段8,自定义字段9,自定义字段10,现金项目编号,现金借方,现金贷方
0,7,记,1,NaN,1,NaN,-1,张文伟,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,7,记,1,NaN,2,NaN,-1,张文伟,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,7,记,1,NaN,3,NaN,-1,张文伟,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,7,记,1,NaN,4,NaN,-1,张文伟,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,7,记,1,NaN,5,NaN,-1,张文伟,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,7,记,1,NaN,84,NaN,-1,张文伟,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84,7,记,1,NaN,85,NaN,-1,张文伟,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
85,7,记,1,NaN,86,NaN,-1,张文伟,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
86,7,记,1,NaN,87,NaN,-1,张文伟,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
87,7,记,1,NaN,88,NaN,-1,张文伟,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
df_pinzhen['数量贷方'] = df2['出库'].to_list()
df_pinzhen['数量贷方']

0        -14.0
1         34.0
2        200.0
3        504.0
4         34.0
        ...
83        44.0
84    332762.0
85    522500.0
86     14100.0
87         NaN
Name: 数量贷方, Length: 88, dtype: float64

In [24]:
df_pinzhen['数量贷方'] = df_pinzhen['数量贷方'].fillna(0)

In [25]:
df_pinzhen.to_excel('111.xlsx',index = False)
os.startfile('111.xlsx')

In [26]:
msg = '请点选原材料出库文件"原材料出库2022-07.xlsx"'
fname1 = easygui.fileopenbox(msg)
fname1

'F:\\a00nutstore\\006\\zw\\2022\\202207\\原材料出库2022-07.xlsx'

In [27]:
df1 = pd.read_excel(fname1)
df1

          科目编码      科目名称        出库          单价          金额
0   1403001001   70g双胶大度     -14.0  186.426548    -2609.97
1   1403001005   98g双胶正度      34.0  240.168142     8165.72
2   1403001008   74g双胶正度     200.0  185.613115    37122.62
3   1403001013   80g双胶正度     504.0  189.784969    95651.62
4   1403001015  100g双胶正度      34.0  245.080378     8332.73
..         ...       ...       ...         ...         ...
84  1403006008        胶套  332762.0    0.509542   169556.22
85  1403006009       空白袋  522500.0    0.049371    25796.52
86  1403006010        书套   14100.0    0.046190      651.28
87     包装物  小计       NaN       NaN         NaN   435611.06
88         原材料        合计       NaN         NaN  7657598.12

[89 rows x 5 columns]

In [29]:
path, file = os.path.split(fname1)
path

'F:\\a00nutstore\\006\\zw\\2022\\202207'

In [30]:
path, file = os.path.split(fname1)

In [1]:
file = '原材料出库2022-07.xlsx'

In [12]:
period = int(file.split('.')[0].split('-')[-1])
period

7

In [16]:
a = '%02d'%period
a

'702d'

In [8]:
a = ':02d{}'.format(period)
a|

SyntaxError: invalid syntax (2257300943.py, line 2)